using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Sdp.SourceGenerator.Generators;

internal static partial class CsvMapperEmitter
{
    public static string Emit(RecordAnalysis analysis)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var scope = GeneratorEmitHelper.OpenNamespaceAndContainingTypes(sb, analysis.Symbol);
        var indent = scope.Indent;

        // '    partial record FooRecord'
        var recordKeyword = GeneratorEmitHelper.GetTypeKeyword(analysis.Symbol);
        sb.Append(indent).Append("partial ").Append(recordKeyword).Append(' ')
            .AppendLine(GeneratorEmitHelper.EscapeIdentifier(analysis.TypeName));
        sb.Append(indent).AppendLine("{");

        var memberIndent = indent + "    ";
        if (analysis.CanEmit)
        {
            var nestedTokens = BuildNestedTokenMap(analysis.Parameters);
            EmitMapper(sb, analysis, memberIndent, nestedTokens);
            EmitHelpers(sb, analysis.Parameters, memberIndent, nestedTokens);
        }
        else
        {
            EmitNotSupportedShell(sb, analysis, memberIndent);
        }

        sb.Append(indent).AppendLine("}");
        GeneratorEmitHelper.CloseContainingTypes(sb, scope);

        return sb.ToString();
    }

    private static void EmitNotSupportedShell(StringBuilder sb, RecordAnalysis analysis, string indent)
    {
        sb.Append(indent).Append("internal static ").Append(analysis.FullyQualifiedTypeName).AppendLine(" MapFromCsvRow(");
        sb.Append(indent).AppendLine("    global::Sdp.Csv.CsvHeaderIndex headers,");
        sb.Append(indent).AppendLine("    string[] values)");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).Append("    throw new global::System.NotSupportedException(\"")
            .Append("Sdp.SourceGenerator: '").Append(analysis.FullyQualifiedTypeName)
            .AppendLine("' has parameter type(s) not yet supported by the CSV mapper.\");");
        sb.Append(indent).AppendLine("}");
    }

    private static void EmitMapper(
        StringBuilder sb,
        RecordAnalysis analysis,
        string indent,
        Dictionary<INamedTypeSymbol, string> nestedTokens)
    {
        sb.Append(indent).Append("internal static ").Append(analysis.FullyQualifiedTypeName).AppendLine(" MapFromCsvRow(");
        sb.Append(indent).AppendLine("    global::Sdp.Csv.CsvHeaderIndex headers,");
        sb.Append(indent).AppendLine("    string[] values)");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).Append("    return new ").Append(analysis.FullyQualifiedTypeName).AppendLine("(");

        for (var i = 0; i < analysis.Parameters.Length; i++)
        {
            var param = analysis.Parameters[i];
            sb.Append(indent).Append("        ");
            sb.Append(GeneratorEmitHelper.EscapeIdentifier(param.Name)).Append(": ");
            sb.Append(EmitConversion(param, basePathVar: null, ownerToken: string.Empty, nestedTokens));

            if (i < analysis.Parameters.Length - 1)
            {
                sb.Append(',');
            }

            sb.AppendLine();
        }

        sb.Append(indent).AppendLine("    );");
        sb.Append(indent).AppendLine("}");
    }

    // 예)
    // public sealed partial record QuestRecord(
    //     int Id,                                                          // 어느 분기에도 해당 없음
    //     RewardInfo Reward,                                               // 분기 1: 중첩 record
    //     ImmutableArray<StageInfo> Stages,                                // 분기 2: 컬렉션 원소 record
    //     FrozenDictionary<int, NpcInfo> Npcs,                             // 분기 3: dict 값 record
    //     [SingleColumnCollection(",")] ImmutableArray<Element> Elements); // 분기 4: 원소 enum
    //
    // public sealed partial record RewardInfo(ItemId Item, int Count);     // 중첩 안의 중첩
    // public sealed partial record ItemId(long Value);
    // public sealed partial record StageInfo(int Stage);
    // public sealed partial record NpcInfo([Key] int NpcId, string Name);
    // public enum Element { Fire, Water, }
    //
    // 타입별 고유 토큰("일련번호_타입명")이 필요한 경우 map에 넣고 반환
    // int Id 처럼 인라인 파싱식으로 끝나는 스칼라는 전용 헬퍼가 없으므로 맵에 들어가지 않는다.
    // map = {
    //     RewardInfo : "1_RewardInfo",
    //     ItemId     : "2_ItemId",
    //     StageInfo  : "3_StageInfo",
    //     NpcInfo    : "4_NpcInfo",
    //     Element    : "5_Element",
    // }
    //
    // 토큰          | 생성되는 헬퍼               | 호출하는 쪽
    // 1_RewardInfo | __MapNested_1_RewardInfo   | MapFromCsvRow 의 Reward: 인자
    // 2_ItemId     | __MapNested_2_ItemId       | __MapNested_1_RewardInfo 내부
    // 3_StageInfo  | __MapNested_3_StageInfo    | __MapArray_Stages 의 원소 변환
    // 4_NpcInfo    | __MapNested_4_NpcInfo      | __MapDict_Npcs 의 값 변환
    // 5_Element    | __MapElementEnum_5_Element | __MapSingleArray_Elements 의 조각 변환
    private static Dictionary<INamedTypeSymbol, string> BuildNestedTokenMap(ImmutableArray<ParameterAnalysis> parameters)
    {
        // Roslyn 심볼은 참조 동일성이 보장되지 않아 전용 비교자가 필요 (같은 타입 다른 인스턴스 상황이나 nullable에서 문제 발생)
        var map = new Dictionary<INamedTypeSymbol, string>(SymbolEqualityComparer.Default);
        CollectNestedTokens(parameters, map);
        return map;
    }

    private static void CollectNestedTokens(
        ImmutableArray<ParameterAnalysis> parameters,
        Dictionary<INamedTypeSymbol, string> map)
    {
        // 타입별 고유 토큰("일련번호_타입명")이 필요한 경우 map에 넣고 반환
        foreach (var param in parameters)
        {
            // 중첩 레코드
            if (param.Nested is { } nested && !map.ContainsKey(nested.Symbol))
            {
                map[nested.Symbol] = MakeToken(nested.Symbol.Name, map);
                CollectNestedTokens(nested.Parameters, map);
            }

            // 컬렉션된 원소 레코드
            if (param.Collection is { ElementNested: { } elementNested }
                && !map.ContainsKey(elementNested.Symbol))
            {
                map[elementNested.Symbol] = MakeToken(elementNested.Symbol.Name, map);
                CollectNestedTokens(elementNested.Parameters, map);
            }

            // dict의 값 레코드
            if (param.Collection is { Kind: CollectionKind.FrozenDictionary } collection
                && collection.ValueNested is { } valueNested
                && !map.ContainsKey(valueNested.Symbol))
            {
                map[valueNested.Symbol] = MakeToken(valueNested.Symbol.Name, map);
                CollectNestedTokens(valueNested.Parameters, map);
            }

            // 컬렉션된 원소 enum
            if (param.Collection is { ElementKind: ScalarKind.Enum, ElementNested: null } enumCollection)
            {
                var enumType = (INamedTypeSymbol)TypeClassifier.UnwrapNullable(enumCollection.ElementType);
                if (!map.ContainsKey(enumType))
                {
                    map[enumType] = MakeToken(enumType.Name, map);
                }
            }
        }
    }

    private static string MakeToken(string baseName, Dictionary<INamedTypeSymbol, string> map)
    {
        return FormattableString.Invariant($"{map.Count + 1}_{baseName}");
    }

    private static string HelperName(string prefix, string ownerToken, string name)
    {
        if (ownerToken.Length == 0)
        {
            // 루트 파라미터 Level
            // HelperName("__ValidateRange_", "", "Level") → "__ValidateRange_Level"
            return $"{prefix}{name}";
        }

        // 중첩 RewardInfo의 파라미터 Count
        // HelperName("__ValidateRange_", "1_RewardInfo", "Count") → "__ValidateRange_1_RewardInfo_Count"
        return $"{prefix}{ownerToken}_{name}";
    }

    private static void EmitHelpers(
        StringBuilder sb,
        ImmutableArray<ParameterAnalysis> parameters,
        string indent,
        Dictionary<INamedTypeSymbol, string> nestedTokens)
    {
        var emittedHelperTypes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        EmitHelpersRecursive(sb, parameters, emittedHelperTypes, indent, ownerToken: string.Empty, nestedTokens);
    }

    private static void EmitHelpersRecursive(
        StringBuilder sb,
        ImmutableArray<ParameterAnalysis> parameters,
        HashSet<INamedTypeSymbol> emittedHelperTypes,
        string indent,
        string ownerToken,
        Dictionary<INamedTypeSymbol, string> nestedTokens)
    {
        foreach (var param in parameters)
        {
            // 컬렉션 파라미터의 [Range]/[RegularExpression] 는 원소 타입을 기준으로 검증 헬퍼를 만든다.
            var effectiveKind = param.Collection is { } rangeCollection ? rangeCollection.ElementKind : param.Kind;
            var effectiveType = param.Collection is { } typeCollection ? typeCollection.ElementType : param.Type;

            if (param.Kind == ScalarKind.Enum)
            {
                sb.AppendLine();
                EmitEnumHelper(sb, param, indent, ownerToken);
            }

            if (param.Range is { ArgKind: RangeArgKind.Numeric })
            {
                sb.AppendLine();
                EmitNumericRangeHelper(sb, param, effectiveKind, indent, ownerToken);
            }
            else if (param.Range is { ArgKind: RangeArgKind.Typed })
            {
                sb.AppendLine();
                EmitTypedRangeHelper(sb, param, effectiveKind, effectiveType, indent, ownerToken);
            }

            if (param.RegexPattern is not null)
            {
                sb.AppendLine();
                EmitRegexHelper(sb, param, indent, ownerToken);
            }

            if (param.Collection is null && param.Nested is null && !param.IsIgnored
                && param.IsNullable && param.NullString is not null)
            {
                sb.AppendLine();
                EmitNullableScalarHelper(sb, param, indent, ownerToken);
            }

            if (param.Nested is { } nested && emittedHelperTypes.Add(nested.Symbol))
            {
                sb.AppendLine();
                EmitNestedHelper(sb, nested, indent, nestedTokens);
                EmitHelpersRecursive(sb, nested.Parameters, emittedHelperTypes, indent, nestedTokens[nested.Symbol], nestedTokens);
            }

            if (param.Collection is not null)
            {
                sb.AppendLine();

                EmitCollectionElementEnumHelper(sb, param, emittedHelperTypes, indent, nestedTokens);

                if (param.Collection.Kind == CollectionKind.ImmutableArray)
                {
                    EmitCollectionElementNestedHelpers(sb, param, emittedHelperTypes, indent, nestedTokens);
                    EmitArrayHelper(sb, param, indent, ownerToken, nestedTokens);
                }
                else if (param.Collection.Kind == CollectionKind.FrozenSet)
                {
                    EmitCollectionElementNestedHelpers(sb, param, emittedHelperTypes, indent, nestedTokens);
                    EmitSetHelper(sb, param, indent, ownerToken, nestedTokens);
                }
                else if (param.Collection.Kind == CollectionKind.FrozenDictionary)
                {
                    var valueNested = param.Collection.ValueNested!;
                    if (emittedHelperTypes.Add(valueNested.Symbol))
                    {
                        EmitNestedHelper(sb, valueNested, indent, nestedTokens);
                        sb.AppendLine();
                        EmitHelpersRecursive(sb, valueNested.Parameters, emittedHelperTypes, indent, nestedTokens[valueNested.Symbol], nestedTokens);
                    }

                    EmitDictHelper(sb, param, indent, ownerToken, nestedTokens);
                }
                else if (param.Collection.Kind == CollectionKind.SingleColumnImmutableArray)
                {
                    EmitSingleColumnArrayHelper(sb, param, indent, ownerToken, nestedTokens);
                }
                else if (param.Collection.Kind == CollectionKind.SingleColumnFrozenSet)
                {
                    EmitSingleColumnSetHelper(sb, param, indent, ownerToken, nestedTokens);
                }
            }
        }
    }
}
