using System;
using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Sdp.SourceGenerator.Generators;

internal static class CsvMapperEmitter
{
    // 컬렉션 매핑 헬퍼 이름 prefix. EmitConversion 의 호출부와 각 헬퍼 방출부가 같은 이름을 쓰도록
    // 상수로 공유한다 — 한쪽만 바뀌면 생성 코드가 존재하지 않는 헬퍼를 호출하게 된다.
    private const string ArrayHelperPrefix = "__MapArray_";
    private const string SetHelperPrefix = "__MapSet_";
    private const string DictionaryHelperPrefix = "__MapDict_";
    private const string SingleColumnArrayHelperPrefix = "__MapSingleArray_";
    private const string SingleColumnSetHelperPrefix = "__MapSingleSet_";

    public static string Emit(RecordAnalysis analysis)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var scope = GeneratorEmitHelper.OpenNamespaceAndContainingTypes(sb, analysis.Symbol);
        var indent = scope.Indent;

        var recordKeyword = GeneratorEmitHelper.GetTypeKeyword(analysis.Symbol);
        sb.Append(indent).Append("partial ").Append(recordKeyword).Append(' ')
            .AppendLine(GeneratorEmitHelper.EscapeIdentifier(analysis.TypeName));
        sb.Append(indent).AppendLine("{");

        var memberIndent = indent + "    ";
        if (analysis.CanEmit)
        {
            var nestedTokens = BuildNestedTokenMap(analysis.Parameters);
            EmitMapper(sb, analysis, memberIndent, nestedTokens);
            EmitHelpers(sb, analysis.Parameters, memberIndent, nestedTokens);
        }
        else
        {
            EmitNotSupportedShell(sb, analysis, memberIndent);
        }

        sb.Append(indent).AppendLine("}");
        GeneratorEmitHelper.CloseContainingTypes(sb, scope);

        return sb.ToString();
    }

    private static void EmitNotSupportedShell(StringBuilder sb, RecordAnalysis analysis, string indent)
    {
        sb.Append(indent).Append("internal static ").Append(analysis.FullyQualifiedTypeName).AppendLine(" MapFromCsvRow(");
        sb.Append(indent).AppendLine("    global::Sdp.Csv.CsvHeaderIndex headers,");
        sb.Append(indent).AppendLine("    string[] values)");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).Append("    throw new global::System.NotSupportedException(\"")
            .Append("Sdp.SourceGenerator: '").Append(analysis.FullyQualifiedTypeName)
            .AppendLine("' has parameter type(s) not yet supported by the CSV mapper.\");");
        sb.Append(indent).AppendLine("}");
    }

    private static void EmitMapper(
        StringBuilder sb,
        RecordAnalysis analysis,
        string indent,
        Dictionary<INamedTypeSymbol, string> nestedTokens)
    {
        // CsvLoader 에 메서드 그룹으로 넘기는 진입점. 생성 테이블 코드(같은 어셈블리)가 전달하므로 internal 로 둔다.
        sb.Append(indent).Append("internal static ").Append(analysis.FullyQualifiedTypeName).AppendLine(" MapFromCsvRow(");
        sb.Append(indent).AppendLine("    global::Sdp.Csv.CsvHeaderIndex headers,");
        sb.Append(indent).AppendLine("    string[] values)");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).Append("    return new ").Append(analysis.FullyQualifiedTypeName).AppendLine("(");

        for (var i = 0; i < analysis.Parameters.Length; i++)
        {
            var param = analysis.Parameters[i];
            sb.Append(indent).Append("        ");
            sb.Append(GeneratorEmitHelper.EscapeIdentifier(param.Name)).Append(": ");
            sb.Append(EmitConversion(param, basePathVar: null, ownerToken: string.Empty, nestedTokens));

            if (i < analysis.Parameters.Length - 1)
            {
                sb.Append(',');
            }

            sb.AppendLine();
        }

        sb.Append(indent).AppendLine("    );");
        sb.Append(indent).AppendLine("}");
    }

    // 중첩 record 타입마다 헬퍼 이름에 쓸 고유 토큰을 부여한다.
    // 토큰은 '일련번호_타입명' 형태다. 일련번호가 타입 간 유일성을 보장하고(서로 다른 네임스페이스의
    // 동명 타입 포함), C# 식별자는 숫자로 시작할 수 없으므로 토큰이 붙은 헬퍼 이름이 토큰 없는
    // root 파라미터 헬퍼 이름과 충돌할 수도 없다 (중첩 A 의 파라미터 B → __ValidateRange_1_A_B,
    // root 파라미터 A_B → __ValidateRange_A_B).
    private static Dictionary<INamedTypeSymbol, string> BuildNestedTokenMap(ImmutableArray<ParameterAnalysis> parameters)
    {
        var map = new Dictionary<INamedTypeSymbol, string>(SymbolEqualityComparer.Default);
        CollectNestedTokens(parameters, map);
        return map;
    }

    private static void CollectNestedTokens(
        ImmutableArray<ParameterAnalysis> parameters,
        Dictionary<INamedTypeSymbol, string> map)
    {
        foreach (var param in parameters)
        {
            if (param.Nested is { } nested && !map.ContainsKey(nested.Symbol))
            {
                map[nested.Symbol] = MakeToken(nested.Symbol.Name, map);
                CollectNestedTokens(nested.Parameters, map);
            }

            if (param.Collection is { Kind: CollectionKind.FrozenDictionary } collection
                && collection.ValueNested is { } valueNested
                && !map.ContainsKey(valueNested.Symbol))
            {
                map[valueNested.Symbol] = MakeToken(valueNested.Symbol.Name, map);
                CollectNestedTokens(valueNested.Parameters, map);
            }

            if (param.Collection is { ElementNested: { } elementNested }
                && !map.ContainsKey(elementNested.Symbol))
            {
                map[elementNested.Symbol] = MakeToken(elementNested.Symbol.Name, map);
                CollectNestedTokens(elementNested.Parameters, map);
            }

            if (param.Collection is { ElementKind: ScalarKind.Enum, ElementNested: null } enumCollection)
            {
                var enumType = (INamedTypeSymbol)TypeClassifier.UnwrapNullable(enumCollection.ElementType);
                if (!map.ContainsKey(enumType))
                {
                    map[enumType] = MakeToken(enumType.Name, map);
                }
            }
        }
    }

    private static string MakeToken(string baseName, Dictionary<INamedTypeSymbol, string> map)
        => (map.Count + 1).ToString(CultureInfo.InvariantCulture) + "_" + baseName;

    private static string NestedToken(Dictionary<INamedTypeSymbol, string> map, INamedTypeSymbol symbol)
        => map[symbol];

    private static string HelperName(string prefix, string ownerToken, string name)
        => ownerToken.Length == 0 ? prefix + name : prefix + ownerToken + "_" + name;

    private static void EmitHelpers(
        StringBuilder sb,
        ImmutableArray<ParameterAnalysis> parameters,
        string indent,
        Dictionary<INamedTypeSymbol, string> nestedTokens)
    {
        var emittedHelperTypes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        EmitHelpersRecursive(sb, parameters, emittedHelperTypes, indent, ownerToken: string.Empty, nestedTokens);
    }

    private static void EmitHelpersRecursive(
        StringBuilder sb,
        ImmutableArray<ParameterAnalysis> parameters,
        HashSet<INamedTypeSymbol> emittedHelperTypes,
        string indent,
        string ownerToken,
        Dictionary<INamedTypeSymbol, string> nestedTokens)
    {
        foreach (var param in parameters)
        {
            // 컬렉션 파라미터의 [Range]/[RegularExpression] 는 원소 타입을 기준으로 검증 헬퍼를 만든다.
            var effectiveKind = param.Collection is { } rangeCollection ? rangeCollection.ElementKind : param.Kind;
            var effectiveType = param.Collection is { } typeCollection ? typeCollection.ElementType : param.Type;

            if (param.Kind == ScalarKind.Enum)
            {
                sb.AppendLine();
                EmitEnumHelper(sb, param, indent, ownerToken);
            }

            if (param.Range is { ArgKind: RangeArgKind.Numeric })
            {
                sb.AppendLine();
                EmitNumericRangeHelper(sb, param, effectiveKind, indent, ownerToken);
            }
            else if (param.Range is { ArgKind: RangeArgKind.Typed })
            {
                sb.AppendLine();
                EmitTypedRangeHelper(sb, param, effectiveKind, effectiveType, indent, ownerToken);
            }

            if (param.RegexPattern is not null)
            {
                sb.AppendLine();
                EmitRegexHelper(sb, param, indent, ownerToken);
            }

            if (param.Collection is null && param.Nested is null && !param.IsIgnored
                && param.IsNullable && param.NullString is not null)
            {
                sb.AppendLine();
                EmitNullableScalarHelper(sb, param, indent, ownerToken);
            }

            if (param.Nested is { } nested && emittedHelperTypes.Add(nested.Symbol))
            {
                sb.AppendLine();
                EmitNestedHelper(sb, nested, indent, nestedTokens);
                EmitHelpersRecursive(sb, nested.Parameters, emittedHelperTypes, indent, NestedToken(nestedTokens, nested.Symbol), nestedTokens);
            }

            if (param.Collection is not null)
            {
                sb.AppendLine();

                EmitCollectionElementEnumHelper(sb, param, emittedHelperTypes, indent, nestedTokens);

                if (param.Collection.Kind == CollectionKind.ImmutableArray)
                {
                    EmitCollectionElementNestedHelpers(sb, param, emittedHelperTypes, indent, nestedTokens);
                    EmitArrayHelper(sb, param, indent, ownerToken, nestedTokens);
                }
                else if (param.Collection.Kind == CollectionKind.FrozenSet)
                {
                    EmitCollectionElementNestedHelpers(sb, param, emittedHelperTypes, indent, nestedTokens);
                    EmitSetHelper(sb, param, indent, ownerToken, nestedTokens);
                }
                else if (param.Collection.Kind == CollectionKind.FrozenDictionary)
                {
                    var valueNested = param.Collection.ValueNested!;
                    if (emittedHelperTypes.Add(valueNested.Symbol))
                    {
                        EmitNestedHelper(sb, valueNested, indent, nestedTokens);
                        sb.AppendLine();
                        EmitHelpersRecursive(sb, valueNested.Parameters, emittedHelperTypes, indent, NestedToken(nestedTokens, valueNested.Symbol), nestedTokens);
                    }

                    EmitDictHelper(sb, param, indent, ownerToken, nestedTokens);
                }
                else if (param.Collection.Kind == CollectionKind.SingleColumnImmutableArray)
                {
                    EmitSingleColumnArrayHelper(sb, param, indent, ownerToken, nestedTokens);
                }
                else if (param.Collection.Kind == CollectionKind.SingleColumnFrozenSet)
                {
                    EmitSingleColumnSetHelper(sb, param, indent, ownerToken, nestedTokens);
                }
            }
        }
    }

    private static void EmitNestedHelper(
        StringBuilder sb,
        NestedRecordInfo info,
        string indent,
        Dictionary<INamedTypeSymbol, string> nestedTokens)
    {
        var typeFullName = info.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var token = NestedToken(nestedTokens, info.Symbol);

        sb.Append(indent).Append("private static ").Append(typeFullName).Append(" __MapNested_").Append(token).AppendLine("(");
        sb.Append(indent).AppendLine("    global::Sdp.Csv.CsvHeaderIndex headers,");
        sb.Append(indent).AppendLine("    string[] values,");
        sb.Append(indent).AppendLine("    string basePath)");
        sb.Append(indent).AppendLine("{");

        // single-param scalar record(type branding) — basePath 자체를 헤더로 직접 매핑.
        if (info.Parameters.Length == 1
            && info.Parameters[0].Nested is null
            && info.Parameters[0].Collection is null
            && info.Parameters[0].Kind != ScalarKind.Unsupported)
        {
            var only = info.Parameters[0];

            // basePath 헤더가 있으면 그것을(브랜딩), 없으면 basePath + "." + 컬럼명으로 폴백한다.
            // 깊은 중첩(예: Middle.Inner.Value)과 Id.Value 형태 하위호환을 모두 처리.
            var columnNameLiteral = SymbolDisplay.FormatLiteral(only.ColumnName, quote: true);
            sb.Append(indent).Append("    var __key = headers.Contains(basePath) ? basePath : basePath + \".\" + ")
                .Append(columnNameLiteral).AppendLine(";");
            sb.Append(indent).AppendLine("    var __raw = values[headers[__key]];");

            // enum 이면 __MapColumn_ 헬퍼 호출이 나간다. 그 헬퍼는 EmitHelpersRecursive 가 같은 토큰으로 방출한다.
            // NullString 분기는 EmitConversion 과 동일하게 __MapNullable_ 헬퍼를 경유한다.
            string conversion;
            if (only.IsNullable && only.NullString is not null)
            {
                conversion = HelperName("__MapNullable_", token, only.Name) + "(__raw)";
            }
            else
            {
                conversion = WrapValidations(only, EmitBaseConversion(only, "__raw", token), token);
            }

            sb.Append(indent).Append("    return new ").Append(typeFullName).Append('(').Append(conversion).AppendLine(");");
            sb.Append(indent).AppendLine("}");
            return;
        }

        sb.Append(indent).Append("    return new ").Append(typeFullName).AppendLine("(");

        for (var i = 0; i < info.Parameters.Length; i++)
        {
            var param = info.Parameters[i];
            sb.Append(indent).Append("        ");
            sb.Append(GeneratorEmitHelper.EscapeIdentifier(param.Name)).Append(": ");
            sb.Append(EmitConversion(param, basePathVar: "basePath", ownerToken: token, nestedTokens));

            if (i < info.Parameters.Length - 1)
            {
                sb.Append(',');
            }

            sb.AppendLine();
        }

        sb.Append(indent).AppendLine("    );");
        sb.Append(indent).AppendLine("}");
    }

    private static void EmitEnumHelper(StringBuilder sb, ParameterAnalysis param, string indent, string ownerToken)
    {
        var enumType = (INamedTypeSymbol)TypeClassifier.UnwrapNullable(param.Type);
        EmitEnumSwitchHelper(sb, enumType, indent, HelperName("__MapColumn_", ownerToken, param.Name), param.IsKey);
    }

    private static void EmitEnumSwitchHelper(
        StringBuilder sb,
        INamedTypeSymbol enumType,
        string indent,
        string helperName,
        bool isKey)
    {
        var enumFullName = enumType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var underlyingKeyword = ScalarTypeKeyword(TypeClassifier.ClassifyScalar(enumType.EnumUnderlyingType!));
        var isUnsigned64 = enumType.EnumUnderlyingType!.SpecialType == SpecialType.System_UInt64;
        var accumulatorKeyword = isUnsigned64 ? "ulong" : "long";
        var accumulatorSuffix = isUnsigned64 ? "UL" : "L";
        var members = enumType
            .GetMembers()
            .OfType<IFieldSymbol>()
            .Where(f => f.IsConst)
            .ToList();

        sb.Append(indent).Append("private static ").Append(enumFullName).Append(' ')
            .Append(helperName).AppendLine("(string value)");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).AppendLine("    switch (value)");
        sb.Append(indent).AppendLine("    {");

        // 멤버명과 underlying 숫자값을 모두 받는다. 리플렉션(Enum.Parse) 없이 동작하도록 case 로 전개.
        var seenNumeric = new HashSet<string>();
        foreach (var member in members)
        {
            sb.Append(indent).Append("        case \"").Append(member.Name).AppendLine("\":");
            var numeric = EnumMemberNumericLiteral(member.ConstantValue);
            if (numeric is not null && seenNumeric.Add(numeric))
            {
                sb.Append(indent).Append("        case \"").Append(numeric).AppendLine("\":");
            }

            sb.Append(indent).Append("            return ").Append(enumFullName).Append('.').Append(member.Name).AppendLine(";");
        }

        sb.Append(indent).AppendLine("        default:");
        if (isKey)
        {
            // [Key] enum 은 정의되지 않은 숫자값/콤마 조합값도 허용한다(원본 Enum.Parse 동작 보존).
            // 멤버명·숫자 토큰을 ','로 분해해 underlying 값으로 OR 한 뒤 캐스팅한다.
            sb.Append(indent).AppendLine("        {");
            sb.Append(indent).Append("            var __acc = 0").Append(accumulatorSuffix).AppendLine(";");
            sb.Append(indent).AppendLine("            var __parts = value.Split(',');");
            sb.Append(indent).AppendLine("            for (var __i = 0; __i < __parts.Length; __i++)");
            sb.Append(indent).AppendLine("            {");
            sb.Append(indent).AppendLine("                switch (__parts[__i].Trim())");
            sb.Append(indent).AppendLine("                {");
            foreach (var member in members)
            {
                var accumulatorLiteral = EnumAccumulatorLiteral(member.ConstantValue, isUnsigned64);
                sb.Append(indent).Append("                    case \"").Append(member.Name).AppendLine("\":");
                sb.Append(indent).Append("                        __acc |= ").Append(accumulatorLiteral).AppendLine(";");
                sb.Append(indent).AppendLine("                        break;");
            }

            sb.Append(indent).AppendLine("                    default:");
            sb.Append(indent).Append("                        __acc |= (").Append(accumulatorKeyword).Append(")(")
                .Append(InvariantIntegerParse(underlyingKeyword, "__parts[__i].Trim()")).AppendLine(");");
            sb.Append(indent).AppendLine("                        break;");
            sb.Append(indent).AppendLine("                }");
            sb.Append(indent).AppendLine("            }");
            sb.AppendLine();
            sb.Append(indent).Append("            return (").Append(enumFullName).AppendLine(")__acc;");
            sb.Append(indent).AppendLine("        }");
        }
        else
        {
            sb.Append(indent).Append("            throw new global::System.ArgumentException($\"'{value}' is not a defined member of ")
                .Append(enumFullName).AppendLine(".\", nameof(value));");
        }

        sb.Append(indent).AppendLine("    }");
        sb.Append(indent).AppendLine("}");
    }

    private static string? EnumMemberNumericLiteral(object? constantValue)
    {
        // ulong 백킹 enum 의 long.MaxValue 초과 멤버는 Convert.ToInt64 가 오버플로하므로 분리해 포맷한다.
        return constantValue switch
        {
            null => null,
            ulong u => u.ToString(CultureInfo.InvariantCulture),
            _ => System.Convert.ToInt64(constantValue, CultureInfo.InvariantCulture)
                .ToString(CultureInfo.InvariantCulture),
        };
    }

    private static string EnumAccumulatorLiteral(object? constantValue, bool isUnsigned64)
    {
        // [Key] enum 폴백 누산기에 OR 할 멤버 리터럴. 부호 비트가 켜진 long 백킹 멤버(long.MinValue 등)는
        // 음수 십진 리터럴로 표기하면 컴파일되지 않으므로 2의 보수 비트 패턴을 unchecked 캐스트로 방출한다.
        if (isUnsigned64)
        {
            var bits = System.Convert.ToUInt64(constantValue, CultureInfo.InvariantCulture);
            return bits.ToString(CultureInfo.InvariantCulture) + "UL";
        }

        var value = System.Convert.ToInt64(constantValue, CultureInfo.InvariantCulture);
        if (value >= 0)
        {
            return value.ToString(CultureInfo.InvariantCulture) + "L";
        }

        var pattern = unchecked((ulong)value).ToString(CultureInfo.InvariantCulture);
        return "unchecked((long)" + pattern + "UL)";
    }

    private static string EmitConversion(
        ParameterAnalysis param,
        string? basePathVar,
        string ownerToken,
        Dictionary<INamedTypeSymbol, string> nestedTokens)
    {
        // [Ignore] 파라미터는 스캐너가 헤더에서 제외하므로 매핑하지 않고 default 를 주입한다.
        if (param.IsIgnored)
        {
            return "default!";
        }

        var keyLiteral = SymbolDisplay.FormatLiteral(param.ColumnName, quote: true);
        var keyExpr = basePathVar is null
            ? keyLiteral
            : $"{basePathVar} + \".\" + {keyLiteral}";
        var valueExpr = $"values[headers[{keyExpr}]]";

        if (param.Collection is not null)
        {
            var helperPrefix = param.Collection.Kind switch
            {
                CollectionKind.ImmutableArray => ArrayHelperPrefix,
                CollectionKind.FrozenSet => SetHelperPrefix,
                CollectionKind.FrozenDictionary => DictionaryHelperPrefix,
                CollectionKind.SingleColumnImmutableArray => SingleColumnArrayHelperPrefix,
                CollectionKind.SingleColumnFrozenSet => SingleColumnSetHelperPrefix,
                _ => throw new InvalidOperationException(FormattableString.Invariant(
                    $"Unsupported collection kind: {param.Collection.Kind}")),
            };
            var basePathArg = basePathVar ?? "string.Empty";
            return $"{HelperName(helperPrefix, ownerToken, param.Name)}(headers, values, {basePathArg})";
        }

        if (param.Nested is { } nested)
        {
            return $"__MapNested_{NestedToken(nestedTokens, nested.Symbol)}(headers, values, {keyExpr})";
        }

        // NullString 분기는 같은 셀(헤더 조회 + 인덱싱)을 두 번 읽지 않도록 헬퍼를 경유한다.
        if (param.IsNullable && param.NullString is not null)
        {
            return $"{HelperName("__MapNullable_", ownerToken, param.Name)}({valueExpr})";
        }

        var baseConversion = EmitBaseConversion(param, valueExpr, ownerToken);
        return WrapValidations(param, baseConversion, ownerToken);
    }

    private static string WrapValidations(ParameterAnalysis param, string inner, string ownerToken)
    {
        if (param.Range is not null)
        {
            inner = $"{HelperName("__ValidateRange_", ownerToken, param.Name)}({inner})";
        }

        if (param.RegexPattern is not null)
        {
            inner = $"{HelperName("__ValidatePattern_", ownerToken, param.Name)}({inner})";
        }

        return inner;
    }

    private static string EmitBaseConversion(ParameterAnalysis param, string valueExpr, string ownerToken)
    {
        if (param.Kind == ScalarKind.Enum)
        {
            return $"{HelperName("__MapColumn_", ownerToken, param.Name)}({valueExpr})";
        }

        return EmitScalarParse(param.Kind, valueExpr, param.DateTimeFormat, param.TimeSpanFormat);
    }

    private static string EmitScalarParse(ScalarKind kind, string valueExpr, string? dateTimeFormat = null, string? timeSpanFormat = null)
    {
        return kind switch
        {
            ScalarKind.Bool => $"bool.Parse({valueExpr})",
            ScalarKind.Byte => InvariantIntegerParse("byte", valueExpr),
            ScalarKind.SByte => InvariantIntegerParse("sbyte", valueExpr),
            ScalarKind.Int16 => InvariantIntegerParse("short", valueExpr),
            ScalarKind.UInt16 => InvariantIntegerParse("ushort", valueExpr),
            ScalarKind.Int32 => InvariantIntegerParse("int", valueExpr),
            ScalarKind.UInt32 => InvariantIntegerParse("uint", valueExpr),
            ScalarKind.Int64 => InvariantIntegerParse("long", valueExpr),
            ScalarKind.UInt64 => InvariantIntegerParse("ulong", valueExpr),
            ScalarKind.Single => InvariantFloatParse("float", valueExpr),
            ScalarKind.Double => InvariantFloatParse("double", valueExpr),
            ScalarKind.Decimal => InvariantDecimalParse(valueExpr),
            ScalarKind.String => valueExpr,
            ScalarKind.Char => $"char.Parse({valueExpr})",
            ScalarKind.Guid => $"global::System.Guid.Parse({valueExpr}, global::System.Globalization.CultureInfo.InvariantCulture)",
            ScalarKind.DateTime => InvariantParseExact("global::System.DateTime", valueExpr, dateTimeFormat!),
            ScalarKind.DateTimeOffset => InvariantParseExact("global::System.DateTimeOffset", valueExpr, dateTimeFormat!),
            ScalarKind.DateOnly => InvariantParseExact("global::System.DateOnly", valueExpr, dateTimeFormat!),
            ScalarKind.TimeOnly => InvariantParseExact("global::System.TimeOnly", valueExpr, dateTimeFormat!),
            ScalarKind.TimeSpan => InvariantParseExact("global::System.TimeSpan", valueExpr, timeSpanFormat!),
            _ => valueExpr,
        };
    }

    // nullable 스칼라 + [NullString] 변환 헬퍼. 호출부가 셀 값을 한 번만 읽어 넘기게 한다.
    private static void EmitNullableScalarHelper(StringBuilder sb, ParameterAnalysis param, string indent, string ownerToken)
    {
        var returnType = NullableScalarTypeName(param);
        var nullLiteral = SymbolDisplay.FormatLiteral(param.NullString!, quote: true);
        var conversion = WrapValidations(param, EmitBaseConversion(param, "value", ownerToken), ownerToken);

        sb.Append(indent).Append("private static ").Append(returnType).Append(' ')
            .Append(HelperName("__MapNullable_", ownerToken, param.Name)).AppendLine("(string value)");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).Append("    if (value == ").Append(nullLiteral).AppendLine(")");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        return null;");
        sb.Append(indent).AppendLine("    }");
        sb.AppendLine();
        sb.Append(indent).Append("    return ").Append(conversion).AppendLine(";");
        sb.Append(indent).AppendLine("}");
    }

    private static string NullableScalarTypeName(ParameterAnalysis param)
    {
        if (param.Kind == ScalarKind.Enum)
        {
            var enumName = TypeClassifier.UnwrapNullable(param.Type).ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return enumName + "?";
        }

        return ScalarTypeKeyword(param.Kind) + "?";
    }

    private static string ScalarTypeKeyword(ScalarKind kind)
    {
        return kind switch
        {
            ScalarKind.Bool => "bool",
            ScalarKind.Byte => "byte",
            ScalarKind.SByte => "sbyte",
            ScalarKind.Int16 => "short",
            ScalarKind.UInt16 => "ushort",
            ScalarKind.Int32 => "int",
            ScalarKind.UInt32 => "uint",
            ScalarKind.Int64 => "long",
            ScalarKind.UInt64 => "ulong",
            ScalarKind.Single => "float",
            ScalarKind.Double => "double",
            ScalarKind.Decimal => "decimal",
            ScalarKind.String => "string",
            ScalarKind.Char => "char",
            ScalarKind.Guid => "global::System.Guid",
            ScalarKind.DateTime => "global::System.DateTime",
            ScalarKind.DateTimeOffset => "global::System.DateTimeOffset",
            ScalarKind.DateOnly => "global::System.DateOnly",
            ScalarKind.TimeOnly => "global::System.TimeOnly",
            ScalarKind.TimeSpan => "global::System.TimeSpan",
            _ => "object",
        };
    }

    private static string InvariantIntegerParse(string typeKeyword, string valueExpr)
        => $"{typeKeyword}.Parse({valueExpr}, global::System.Globalization.NumberStyles.Integer, global::System.Globalization.CultureInfo.InvariantCulture)";

    private static string InvariantFloatParse(string typeKeyword, string valueExpr)
        => $"{typeKeyword}.Parse({valueExpr}, global::System.Globalization.NumberStyles.Float | global::System.Globalization.NumberStyles.AllowThousands, global::System.Globalization.CultureInfo.InvariantCulture)";

    private static string InvariantDecimalParse(string valueExpr)
        => $"decimal.Parse({valueExpr}, global::System.Globalization.NumberStyles.Number, global::System.Globalization.CultureInfo.InvariantCulture)";

    private static string InvariantParseExact(string typeName, string valueExpr, string format)
    {
        var formatLiteral = SymbolDisplay.FormatLiteral(format, quote: true);
        return $"{typeName}.ParseExact({valueExpr}, {formatLiteral}, global::System.Globalization.CultureInfo.InvariantCulture)";
    }

    private static void EmitNumericRangeHelper(StringBuilder sb, ParameterAnalysis param, ScalarKind kind, string indent, string ownerToken)
    {
        var typeKeyword = ScalarTypeKeyword(kind);
        var rawMin = SymbolDisplay.FormatPrimitive(param.Range!.Minimum!, quoteStrings: false, useHexadecimalNumbers: false);
        var rawMax = SymbolDisplay.FormatPrimitive(param.Range!.Maximum!, quoteStrings: false, useHexadecimalNumbers: false);

        // 파라미터 타입과 다른 정밀도의 리터럴이 비교 시 승격되며 경계값이 잘못 거부되는 것을 막기 위해
        // 리터럴을 파라미터 타입 접미사로 고정한다. 경계 비교는 포함(inclusive)이므로 별도 허용오차는 두지 않는다.
        var suffix = kind switch
        {
            ScalarKind.Decimal => "m",
            ScalarKind.Single => "f",
            ScalarKind.Double => "d",
            _ => string.Empty,
        };
        var lowerBound = rawMin + suffix;
        var upperBound = rawMax + suffix;

        sb.Append(indent).Append("private static ").Append(typeKeyword).Append(' ')
            .Append(HelperName("__ValidateRange_", ownerToken, param.Name)).Append('(').Append(typeKeyword).AppendLine(" value)");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).Append("    if (value < ").Append(lowerBound).Append(" || value > ").Append(upperBound).AppendLine(")");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).Append("        throw new global::System.ArgumentOutOfRangeException(nameof(value), value, \"'");
        sb.Append(param.Name).Append("' must be within [").Append(rawMin).Append(", ").Append(rawMax).AppendLine("].\");");
        sb.Append(indent).AppendLine("    }");
        sb.AppendLine();
        sb.Append(indent).AppendLine("    return value;");
        sb.Append(indent).AppendLine("}");
    }

    private static void EmitTypedRangeHelper(StringBuilder sb, ParameterAnalysis param, ScalarKind kind, ITypeSymbol type, string indent, string ownerToken)
    {
        if (kind == ScalarKind.String)
        {
            EmitStringRangeHelper(sb, param, indent, ownerToken);
        }
        else if (kind == ScalarKind.Enum)
        {
            EmitEnumRangeHelper(sb, param, type, indent, ownerToken);
        }
        else
        {
            // DateTime/DateTimeOffset/TimeSpan/숫자 : min/max 문자열을 값 타입으로 한 번만 파싱해 비교한다.
            EmitParsedBoundRangeHelper(sb, param, kind, indent, ownerToken);
        }
    }

    private static void EmitParsedBoundRangeHelper(StringBuilder sb, ParameterAnalysis param, ScalarKind kind, string indent, string ownerToken)
    {
        var typeKeyword = ScalarTypeKeyword(kind);
        var minText = (string)param.Range!.Minimum!;
        var maxText = (string)param.Range!.Maximum!;
        var minLiteral = SymbolDisplay.FormatLiteral(minText, quote: true);
        var maxLiteral = SymbolDisplay.FormatLiteral(maxText, quote: true);
        var minExpr = EmitScalarParse(kind, minLiteral, param.DateTimeFormat, param.TimeSpanFormat);
        var maxExpr = EmitScalarParse(kind, maxLiteral, param.DateTimeFormat, param.TimeSpanFormat);
        var minField = HelperName("__RangeMin_", ownerToken, param.Name);
        var maxField = HelperName("__RangeMax_", ownerToken, param.Name);

        sb.Append(indent).Append("private static readonly ").Append(typeKeyword).Append(' ').Append(minField)
            .Append(" = ").Append(minExpr).AppendLine(";");
        sb.Append(indent).Append("private static readonly ").Append(typeKeyword).Append(' ').Append(maxField)
            .Append(" = ").Append(maxExpr).AppendLine(";");
        sb.AppendLine();
        sb.Append(indent).Append("private static ").Append(typeKeyword).Append(' ')
            .Append(HelperName("__ValidateRange_", ownerToken, param.Name)).Append('(').Append(typeKeyword).AppendLine(" value)");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).Append("    if (value < ").Append(minField).Append(" || value > ").Append(maxField).AppendLine(")");
        sb.Append(indent).AppendLine("    {");
        AppendRangeMessage(sb, indent, param, minText, maxText);
        sb.Append(indent).AppendLine("    }");
        sb.AppendLine();
        sb.Append(indent).AppendLine("    return value;");
        sb.Append(indent).AppendLine("}");
    }

    private static void EmitStringRangeHelper(StringBuilder sb, ParameterAnalysis param, string indent, string ownerToken)
    {
        var minText = (string)param.Range!.Minimum!;
        var maxText = (string)param.Range!.Maximum!;
        var minLiteral = SymbolDisplay.FormatLiteral(minText, quote: true);
        var maxLiteral = SymbolDisplay.FormatLiteral(maxText, quote: true);

        sb.Append(indent).Append("private static string ")
            .Append(HelperName("__ValidateRange_", ownerToken, param.Name)).AppendLine("(string value)");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).Append("    if (string.CompareOrdinal(value, ").Append(minLiteral)
            .Append(") < 0 || string.CompareOrdinal(value, ").Append(maxLiteral).AppendLine(") > 0)");
        sb.Append(indent).AppendLine("    {");
        AppendRangeMessage(sb, indent, param, minText, maxText);
        sb.Append(indent).AppendLine("    }");
        sb.AppendLine();
        sb.Append(indent).AppendLine("    return value;");
        sb.Append(indent).AppendLine("}");
    }

    private static void EmitEnumRangeHelper(StringBuilder sb, ParameterAnalysis param, ITypeSymbol type, string indent, string ownerToken)
    {
        var enumType = (INamedTypeSymbol)TypeClassifier.UnwrapNullable(type);
        var enumFullName = enumType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var isUnsigned64 = enumType.EnumUnderlyingType!.SpecialType == SpecialType.System_UInt64;
        var accumulatorKeyword = isUnsigned64 ? "ulong" : "long";
        var accumulatorSuffix = isUnsigned64 ? "UL" : "L";
        var minExpr = EnumBoundExpr(enumType, enumFullName, param.Range!.Minimum, accumulatorKeyword, accumulatorSuffix);
        var maxExpr = EnumBoundExpr(enumType, enumFullName, param.Range!.Maximum, accumulatorKeyword, accumulatorSuffix);
        var minText = param.Range!.Minimum?.ToString() ?? string.Empty;
        var maxText = param.Range!.Maximum?.ToString() ?? string.Empty;

        sb.Append(indent).Append("private static ").Append(enumFullName).Append(' ')
            .Append(HelperName("__ValidateRange_", ownerToken, param.Name)).Append('(').Append(enumFullName).AppendLine(" value)");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).Append("    var __v = (").Append(accumulatorKeyword).AppendLine(")value;");
        sb.Append(indent).Append("    if (__v < ").Append(minExpr).Append(" || __v > ").Append(maxExpr).AppendLine(")");
        sb.Append(indent).AppendLine("    {");
        AppendRangeMessage(sb, indent, param, minText, maxText);
        sb.Append(indent).AppendLine("    }");
        sb.AppendLine();
        sb.Append(indent).AppendLine("    return value;");
        sb.Append(indent).AppendLine("}");
    }

    // [Range] 위반 메시지에 박는 min/max 는 사용자 attribute 문자열이므로 메시지 전체를 리터럴로 escape 한다.
    private static void AppendRangeMessage(StringBuilder sb, string indent, ParameterAnalysis param, string minText, string maxText)
    {
        var message = "'" + param.Name + "' must be within [" + minText + ", " + maxText + "].";
        var messageLiteral = SymbolDisplay.FormatLiteral(message, quote: true);
        sb.Append(indent).Append("        throw new global::System.ArgumentOutOfRangeException(nameof(value), value, ");
        sb.Append(messageLiteral).AppendLine(");");
    }

    private static string EnumBoundExpr(INamedTypeSymbol enumType, string enumFullName, object? bound, string accumulatorKeyword, string accumulatorSuffix)
    {
        var text = bound as string ?? bound?.ToString() ?? "0";
        var isMember = enumType.GetMembers()
            .OfType<IFieldSymbol>()
            .Any(f => f.IsConst && f.Name == text);
        if (isMember)
        {
            return "(" + accumulatorKeyword + ")" + enumFullName + "." + text;
        }

        return text + accumulatorSuffix;
    }

    private static void EmitRegexHelper(StringBuilder sb, ParameterAnalysis param, string indent, string ownerToken)
    {
        var patternLiteral = SymbolDisplay.FormatLiteral(param.RegexPattern!, quote: true);
        var patternField = HelperName("__Pattern_", ownerToken, param.Name);

        sb.Append(indent).Append("private static readonly global::System.Text.RegularExpressions.Regex ").Append(patternField).AppendLine(" =");
        sb.Append(indent).Append("    new global::System.Text.RegularExpressions.Regex(").Append(patternLiteral).AppendLine(");");
        sb.AppendLine();
        sb.Append(indent).Append("private static string ").Append(HelperName("__ValidatePattern_", ownerToken, param.Name)).AppendLine("(string value)");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).Append("    if (!").Append(patternField).AppendLine(".IsMatch(value))");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).Append("        throw new global::System.ArgumentException($\"'{value}' does not match pattern for '");
        sb.Append(param.Name).AppendLine("'.\", nameof(value));");
        sb.Append(indent).AppendLine("    }");
        sb.AppendLine();
        sb.Append(indent).AppendLine("    return value;");
        sb.Append(indent).AppendLine("}");
    }

    private static void EmitCollectionElementNestedHelpers(
        StringBuilder sb,
        ParameterAnalysis param,
        HashSet<INamedTypeSymbol> emittedHelperTypes,
        string indent,
        Dictionary<INamedTypeSymbol, string> nestedTokens)
    {
        if (param.Collection?.ElementNested is { } elementNested && emittedHelperTypes.Add(elementNested.Symbol))
        {
            EmitNestedHelper(sb, elementNested, indent, nestedTokens);
            sb.AppendLine();
            EmitHelpersRecursive(sb, elementNested.Parameters, emittedHelperTypes, indent, NestedToken(nestedTokens, elementNested.Symbol), nestedTokens);
            sb.AppendLine();
        }
    }

    // 컬렉션 원소가 enum 인 경우, 원소 타입별로 한 번만 enum 파싱 스위치 헬퍼를 방출한다.
    private static void EmitCollectionElementEnumHelper(
        StringBuilder sb,
        ParameterAnalysis param,
        HashSet<INamedTypeSymbol> emittedHelperTypes,
        string indent,
        Dictionary<INamedTypeSymbol, string> nestedTokens)
    {
        if (param.Collection is not { ElementKind: ScalarKind.Enum, ElementNested: null } info)
        {
            return;
        }

        var enumType = (INamedTypeSymbol)TypeClassifier.UnwrapNullable(info.ElementType);
        if (!emittedHelperTypes.Add(enumType))
        {
            return;
        }

        EmitEnumSwitchHelper(sb, enumType, indent, "__MapElementEnum_" + NestedToken(nestedTokens, enumType), isKey: false);
        sb.AppendLine();
    }

    private static string ElementTypeName(CollectionInfo info)
    {
        if (info.ElementNested is not null)
        {
            return info.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        var keyword = info.ElementKind == ScalarKind.Enum
            ? TypeClassifier.UnwrapNullable(info.ElementType).ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            : ScalarTypeKeyword(info.ElementKind);
        return TypeClassifier.IsNullable(info.ElementType) ? keyword + "?" : keyword;
    }

    // 고정 길이(__k0 …)와 동적 길이(__ek) 양쪽에서 헤더 키 변수/식을 받아 원소 변환식을 만든다.
    private static string EmitColumnElementConversion(
        ParameterAnalysis param,
        string keyExpression,
        string ownerToken,
        Dictionary<INamedTypeSymbol, string> nestedTokens)
    {
        var info = param.Collection!;
        if (info.ElementNested is { } elementNested)
        {
            return $"__MapNested_{NestedToken(nestedTokens, elementNested.Symbol)}(headers, values, {keyExpression})";
        }

        var valueExpr = $"values[headers[{keyExpression}]]";
        var baseConversion = EmitElementBaseConversion(info, valueExpr, param, nestedTokens);

        // [Range]/[RegularExpression] 가 컬렉션에 붙으면 원소를 각각 검증한다. 검증 attribute 가 붙은
        // nullable 원소 컬렉션은 IsElementValidationCompatible 이 emit 자체를 거부하므로, nullable 원소가
        // 여기 도달하는 경우 WrapValidations 는 no-op 이다.
        var converted = WrapValidations(param, baseConversion, ownerToken);

        if (TypeClassifier.IsNullable(info.ElementType) && param.NullString is not null)
        {
            var nullLiteral = SymbolDisplay.FormatLiteral(param.NullString, quote: true);
            return $"({valueExpr} == {nullLiteral} ? {EmitElementNullCast(info)} : {converted})";
        }

        return converted;
    }

    private static string EmitElementBaseConversion(
        CollectionInfo info,
        string valueExpr,
        ParameterAnalysis param,
        Dictionary<INamedTypeSymbol, string> nestedTokens)
    {
        if (info.ElementKind == ScalarKind.Enum)
        {
            var enumType = (INamedTypeSymbol)TypeClassifier.UnwrapNullable(info.ElementType);
            return $"__MapElementEnum_{NestedToken(nestedTokens, enumType)}({valueExpr})";
        }

        return EmitScalarParse(info.ElementKind, valueExpr, param.DateTimeFormat, param.TimeSpanFormat);
    }

    private static string EmitElementNullCast(CollectionInfo info)
    {
        if (info.ElementKind == ScalarKind.Enum)
        {
            var enumName = TypeClassifier.UnwrapNullable(info.ElementType).ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return $"({enumName}?)null";
        }

        return $"({ScalarTypeKeyword(info.ElementKind)}?)null";
    }

    // 컬렉션 헬퍼는 basePath 를 받아 절대 헤더(root)와 중첩 헤더(basePath + "." + 절대키)를 모두 처리한다.
    private static void EmitKeyVar(StringBuilder sb, string indent, string keyVar, string absoluteKey)
    {
        var absoluteKeyLiteral = SymbolDisplay.FormatLiteral(absoluteKey, quote: true);
        sb.Append(indent).Append("    var ").Append(keyVar)
            .Append(" = basePath.Length == 0 ? ").Append(absoluteKeyLiteral)
            .Append(" : basePath + \".\" + ").Append(absoluteKeyLiteral).AppendLine(";");
    }

    // 동적 길이 컬렉션: 헤더에서 <ColumnName>[i] 인덱스를 모아 0..N-1 을 순회한다.
    // 인덱스가 비연속(gap)이면 throw 한다. 호출부는 이어서 루프 본문과 닫는 중괄호를 방출한다.
    private static void EmitDynamicElementLoopBegin(StringBuilder sb, ParameterAnalysis param, string indent)
    {
        var columnLiteral = SymbolDisplay.FormatLiteral(param.ColumnName, quote: true);
        sb.Append(indent).Append("    var __base = basePath.Length == 0 ? ").Append(columnLiteral)
            .Append(" : basePath + \".\" + ").Append(columnLiteral).AppendLine(";");
        sb.Append(indent).AppendLine("    var __prefix = __base + \"[\";");
        sb.Append(indent).AppendLine("    var __indices = new global::System.Collections.Generic.HashSet<int>();");
        sb.Append(indent).AppendLine("    var __max = -1;");
        sb.Append(indent).AppendLine("    foreach (var __h in headers.ColumnNames)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        if (!__h.StartsWith(__prefix, global::System.StringComparison.Ordinal)) { continue; }");
        sb.Append(indent).AppendLine("        var __close = __h.IndexOf(']', __prefix.Length);");
        sb.Append(indent).AppendLine("        if (__close < 0) { continue; }");
        sb.Append(indent).AppendLine("        if (int.TryParse(__h.Substring(__prefix.Length, __close - __prefix.Length), global::System.Globalization.NumberStyles.None, global::System.Globalization.CultureInfo.InvariantCulture, out var __idx)) { __indices.Add(__idx); if (__idx > __max) { __max = __idx; } }");
        sb.Append(indent).AppendLine("    }");
        sb.AppendLine();
        sb.Append(indent).AppendLine("    for (var __i = 0; __i < __indices.Count; __i++)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).Append("        if (!__indices.Contains(__i)) throw new global::System.ArgumentException(global::System.FormattableString.Invariant($\"Non-contiguous index {__i} (max found index {__max}) in collection '")
            .Append(param.Name).AppendLine("'.\"));");
        sb.Append(indent).AppendLine("        var __ek = __base + \"[\" + __i.ToString(global::System.Globalization.CultureInfo.InvariantCulture) + \"]\";");
        sb.AppendLine();
    }

    private static void EmitArrayHelper(StringBuilder sb, ParameterAnalysis param, string indent, string ownerToken, Dictionary<INamedTypeSymbol, string> nestedTokens)
    {
        var info = param.Collection!;
        var elementKeyword = ElementTypeName(info);

        sb.Append(indent).Append("private static global::System.Collections.Immutable.ImmutableArray<")
            .Append(elementKeyword)
            .Append("> ").Append(HelperName(ArrayHelperPrefix, ownerToken, param.Name)).AppendLine("(");
        sb.Append(indent).AppendLine("    global::Sdp.Csv.CsvHeaderIndex headers,");
        sb.Append(indent).AppendLine("    string[] values,");
        sb.Append(indent).AppendLine("    string basePath)");
        sb.Append(indent).AppendLine("{");

        if (info.Length > 0)
        {
            sb.Append(indent).Append("    var builder = global::System.Collections.Immutable.ImmutableArray.CreateBuilder<")
                .Append(elementKeyword).Append(">(").Append(info.Length).AppendLine(");");

            for (var i = 0; i < info.Length; i++)
            {
                var keyVar = "__k" + i.ToString(CultureInfo.InvariantCulture);
                EmitKeyVar(sb, indent, keyVar, param.ColumnName + "[" + i.ToString(CultureInfo.InvariantCulture) + "]");
                var conversion = EmitColumnElementConversion(param, keyVar, ownerToken, nestedTokens);
                sb.Append(indent).Append("    builder.Add(").Append(conversion).AppendLine(");");
            }

            sb.Append(indent).AppendLine("    return builder.MoveToImmutable();");
        }
        else
        {
            sb.Append(indent).Append("    var builder = global::System.Collections.Immutable.ImmutableArray.CreateBuilder<")
                .Append(elementKeyword).AppendLine(">();");
            EmitDynamicElementLoopBegin(sb, param, indent);
            sb.Append(indent).Append("        builder.Add(")
                .Append(EmitColumnElementConversion(param, "__ek", ownerToken, nestedTokens)).AppendLine(");");
            sb.Append(indent).AppendLine("    }");
            sb.Append(indent).AppendLine("    return builder.ToImmutable();");
        }

        sb.Append(indent).AppendLine("}");
    }

    private static void EmitSetHelper(StringBuilder sb, ParameterAnalysis param, string indent, string ownerToken, Dictionary<INamedTypeSymbol, string> nestedTokens)
    {
        var info = param.Collection!;
        var elementKeyword = ElementTypeName(info);

        sb.Append(indent).Append("private static global::System.Collections.Frozen.FrozenSet<")
            .Append(elementKeyword)
            .Append("> ").Append(HelperName(SetHelperPrefix, ownerToken, param.Name)).AppendLine("(");
        sb.Append(indent).AppendLine("    global::Sdp.Csv.CsvHeaderIndex headers,");
        sb.Append(indent).AppendLine("    string[] values,");
        sb.Append(indent).AppendLine("    string basePath)");
        sb.Append(indent).AppendLine("{");

        if (info.Length > 0)
        {
            sb.Append(indent).Append("    var set = new global::System.Collections.Generic.HashSet<")
                .Append(elementKeyword).Append(">(").Append(info.Length).AppendLine(");");

            for (var i = 0; i < info.Length; i++)
            {
                var keyVar = "__k" + i.ToString(CultureInfo.InvariantCulture);
                EmitKeyVar(sb, indent, keyVar, param.ColumnName + "[" + i.ToString(CultureInfo.InvariantCulture) + "]");
                var conversion = EmitColumnElementConversion(param, keyVar, ownerToken, nestedTokens);
                var elementVar = "__e" + i.ToString(CultureInfo.InvariantCulture);
                sb.Append(indent).Append("    var ").Append(elementVar).Append(" = ").Append(conversion).AppendLine(";");
                sb.Append(indent).Append("    if (!set.Add(").Append(elementVar)
                    .Append(")) throw new global::System.ArgumentException(global::System.FormattableString.Invariant($\"Duplicate value {")
                    .Append(elementVar).Append("} in set '")
                    .Append(param.Name).AppendLine("'.\"));");
            }
        }
        else
        {
            sb.Append(indent).Append("    var set = new global::System.Collections.Generic.HashSet<")
                .Append(elementKeyword).AppendLine(">();");
            EmitDynamicElementLoopBegin(sb, param, indent);
            sb.Append(indent).Append("        var __e = ")
                .Append(EmitColumnElementConversion(param, "__ek", ownerToken, nestedTokens)).AppendLine(";");
            sb.Append(indent).Append("        if (!set.Add(__e")
                .Append(")) throw new global::System.ArgumentException(global::System.FormattableString.Invariant($\"Duplicate value {__e} in set '")
                .Append(param.Name).AppendLine("'.\"));");
            sb.Append(indent).AppendLine("    }");
        }

        sb.Append(indent).AppendLine("    return global::System.Collections.Frozen.FrozenSet.ToFrozenSet(set);");
        sb.Append(indent).AppendLine("}");
    }

    private static void EmitDictHelper(
        StringBuilder sb,
        ParameterAnalysis param,
        string indent,
        string ownerToken,
        Dictionary<INamedTypeSymbol, string> nestedTokens)
    {
        var info = param.Collection!;
        var valueNested = info.ValueNested!;

        // enum/record 키는 키워드가 없으므로 FQN 으로 쓴다.
        var keyKeyword = info.KeyKind is ScalarKind.Enum or ScalarKind.Unsupported
            ? info.KeyType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            : ScalarTypeKeyword(info.KeyKind);
        var valueFullName = valueNested.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var keyParam = valueNested.Parameters.Single(nestedParameter => nestedParameter.IsKey);
        var keyMemberAccess = GeneratorEmitHelper.EscapeIdentifier(keyParam.Name);
        var valueToken = NestedToken(nestedTokens, valueNested.Symbol);

        sb.Append(indent).Append("private static global::System.Collections.Frozen.FrozenDictionary<")
            .Append(keyKeyword).Append(", ").Append(valueFullName)
            .Append("> ").Append(HelperName(DictionaryHelperPrefix, ownerToken, param.Name)).AppendLine("(");
        sb.Append(indent).AppendLine("    global::Sdp.Csv.CsvHeaderIndex headers,");
        sb.Append(indent).AppendLine("    string[] values,");
        sb.Append(indent).AppendLine("    string basePath)");
        sb.Append(indent).AppendLine("{");
        if (info.Length > 0)
        {
            sb.Append(indent).Append("    var dict = new global::System.Collections.Generic.Dictionary<")
                .Append(keyKeyword).Append(", ").Append(valueFullName).Append(">(").Append(info.Length).AppendLine(");");

            for (var i = 0; i < info.Length; i++)
            {
                var keyVar = "__k" + i.ToString(CultureInfo.InvariantCulture);
                EmitKeyVar(sb, indent, keyVar, param.ColumnName + "[" + i.ToString(CultureInfo.InvariantCulture) + "]");
                var varName = "__v" + i.ToString(CultureInfo.InvariantCulture);

                sb.Append(indent).Append("    var ").Append(varName).Append(" = __MapNested_")
                    .Append(valueToken).Append("(headers, values, ").Append(keyVar).AppendLine(");");
                sb.Append(indent).Append("    if (!dict.TryAdd(").Append(varName).Append('.').Append(keyMemberAccess).Append(", ").Append(varName)
                    .Append(")) throw new global::System.ArgumentException(global::System.FormattableString.Invariant($\"Duplicate key {")
                    .Append(varName).Append('.').Append(keyMemberAccess).Append("} in dict '").Append(param.Name).AppendLine("'.\"));");
            }
        }
        else
        {
            sb.Append(indent).Append("    var dict = new global::System.Collections.Generic.Dictionary<")
                .Append(keyKeyword).Append(", ").Append(valueFullName).AppendLine(">();");
            EmitDynamicElementLoopBegin(sb, param, indent);
            sb.Append(indent).Append("        var __v = __MapNested_")
                .Append(valueToken).AppendLine("(headers, values, __ek);");
            sb.Append(indent).Append("        if (!dict.TryAdd(__v.").Append(keyMemberAccess)
                .Append(", __v)) throw new global::System.ArgumentException(global::System.FormattableString.Invariant($\"Duplicate key {__v.")
                .Append(keyMemberAccess).Append("} in dict '")
                .Append(param.Name).AppendLine("'.\"));");
            sb.Append(indent).AppendLine("    }");
        }

        sb.Append(indent).AppendLine("    return global::System.Collections.Frozen.FrozenDictionary.ToFrozenDictionary(dict);");
        sb.Append(indent).AppendLine("}");
    }

    private static void EmitSingleColumnArrayHelper(
        StringBuilder sb,
        ParameterAnalysis param,
        string indent,
        string ownerToken,
        Dictionary<INamedTypeSymbol, string> nestedTokens)
    {
        var info = param.Collection!;
        var elementKeyword = ElementTypeName(info);
        var separatorLiteral = SymbolDisplay.FormatLiteral(info.Separator!, quote: true);

        sb.Append(indent).Append("private static global::System.Collections.Immutable.ImmutableArray<")
            .Append(elementKeyword)
            .Append("> ").Append(HelperName(SingleColumnArrayHelperPrefix, ownerToken, param.Name)).AppendLine("(");
        sb.Append(indent).AppendLine("    global::Sdp.Csv.CsvHeaderIndex headers,");
        sb.Append(indent).AppendLine("    string[] values,");
        sb.Append(indent).AppendLine("    string basePath)");
        sb.Append(indent).AppendLine("{");
        EmitKeyVar(sb, indent, "__k", param.ColumnName);
        sb.Append(indent).AppendLine("    var __cell = values[headers[__k]];");
        EmitSingleColumnSplit(sb, param, separatorLiteral, indent);

        EmitCountRangeCheck(sb, param, "parts.Length", indent);

        sb.Append(indent).Append("    var builder = global::System.Collections.Immutable.ImmutableArray.CreateBuilder<")
            .Append(elementKeyword).AppendLine(">(parts.Length);");
        sb.Append(indent).AppendLine("    for (var i = 0; i < parts.Length; i++)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        var __raw = parts[i].Trim();");
        var conversion = EmitElementConversion(param, "__raw", ownerToken, nestedTokens);
        sb.Append(indent).Append("        builder.Add(").Append(conversion).AppendLine(");");
        sb.Append(indent).AppendLine("    }");
        sb.Append(indent).AppendLine("    return builder.MoveToImmutable();");
        sb.Append(indent).AppendLine("}");
    }

    private static void EmitSingleColumnSetHelper(
        StringBuilder sb,
        ParameterAnalysis param,
        string indent,
        string ownerToken,
        Dictionary<INamedTypeSymbol, string> nestedTokens)
    {
        var info = param.Collection!;
        var elementKeyword = ElementTypeName(info);
        var separatorLiteral = SymbolDisplay.FormatLiteral(info.Separator!, quote: true);

        sb.Append(indent).Append("private static global::System.Collections.Frozen.FrozenSet<")
            .Append(elementKeyword)
            .Append("> ").Append(HelperName(SingleColumnSetHelperPrefix, ownerToken, param.Name)).AppendLine("(");
        sb.Append(indent).AppendLine("    global::Sdp.Csv.CsvHeaderIndex headers,");
        sb.Append(indent).AppendLine("    string[] values,");
        sb.Append(indent).AppendLine("    string basePath)");
        sb.Append(indent).AppendLine("{");
        EmitKeyVar(sb, indent, "__k", param.ColumnName);
        sb.Append(indent).AppendLine("    var __cell = values[headers[__k]];");
        EmitSingleColumnSplit(sb, param, separatorLiteral, indent);
        sb.Append(indent).Append("    var set = new global::System.Collections.Generic.HashSet<").Append(elementKeyword).AppendLine(">(parts.Length);");
        sb.Append(indent).AppendLine("    for (var i = 0; i < parts.Length; i++)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        var __raw = parts[i].Trim();");
        var conversion = EmitElementConversion(param, "__raw", ownerToken, nestedTokens);
        sb.Append(indent).Append("        var __e = ").Append(conversion).AppendLine(";");
        sb.Append(indent).Append("        if (!set.Add(__e)) throw new global::System.ArgumentException(global::System.FormattableString.Invariant($\"Duplicate value {__e} in set '")
            .Append(param.Name).AppendLine("'.\"));");
        sb.Append(indent).AppendLine("    }");

        EmitCountRangeCheck(sb, param, "set.Count", indent);

        sb.Append(indent).AppendLine("    return global::System.Collections.Frozen.FrozenSet.ToFrozenSet(set);");
        sb.Append(indent).AppendLine("}");
    }

    // 빈 셀은 기본적으로 빈 컬렉션으로 매핑한다. 단 [NullString("")]이 부착된 nullable 원소 컬렉션이면
    // 빈 셀이 "null 원소 하나"를 의미하므로 단축을 적용하지 않는다 — "".Split 은 빈 문자열 한 조각을
    // 돌려주고, 그 조각이 NullString 과 일치해 null 로 매핑된다.
    private static void EmitSingleColumnSplit(StringBuilder sb, ParameterAnalysis param, string separatorLiteral, string indent)
    {
        var emptyCellMeansNullElement = TypeClassifier.IsNullable(param.Collection!.ElementType)
            && param.NullString is { Length: 0 };
        if (emptyCellMeansNullElement)
        {
            sb.Append(indent).Append("    var parts = __cell.Split(").Append(separatorLiteral).AppendLine(");");
            return;
        }

        sb.Append(indent).Append("    var parts = __cell.Length == 0 ? global::System.Array.Empty<string>() : __cell.Split(").Append(separatorLiteral).AppendLine(");");
    }

    private static string EmitElementConversion(
        ParameterAnalysis param,
        string rawVar,
        string ownerToken,
        Dictionary<INamedTypeSymbol, string> nestedTokens)
    {
        var info = param.Collection!;
        var baseConversion = EmitElementBaseConversion(info, rawVar, param, nestedTokens);
        var converted = WrapValidations(param, baseConversion, ownerToken);

        if (TypeClassifier.IsNullable(info.ElementType) && param.NullString is not null)
        {
            var nullLiteral = SymbolDisplay.FormatLiteral(param.NullString, quote: true);
            return $"({rawVar} == {nullLiteral} ? {EmitElementNullCast(info)} : {converted})";
        }

        return converted;
    }

    private static void EmitCountRangeCheck(StringBuilder sb, ParameterAnalysis param, string countExpr, string indent)
    {
        var info = param.Collection!;
        if (info.MinCount is null || info.MaxCount is null)
        {
            return;
        }

        var minCount = info.MinCount.Value.ToString(CultureInfo.InvariantCulture);
        var maxCount = info.MaxCount.Value.ToString(CultureInfo.InvariantCulture);

        sb.Append(indent).Append("    if (").Append(countExpr).Append(" < ").Append(minCount).Append(" || ").Append(countExpr).Append(" > ").Append(maxCount).AppendLine(")");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).Append("        throw new global::System.ArgumentException(global::System.FormattableString.Invariant($\"Count of '").Append(param.Name)
            .Append("' must be within [").Append(minCount).Append(", ").Append(maxCount)
            .Append("] but was {").Append(countExpr).AppendLine("}.\"));");
        sb.Append(indent).AppendLine("    }");
    }
}
