using System.Text;
using Microsoft.CodeAnalysis;

namespace Sdp.SourceGenerator.Generators;

/// <summary>
/// StaticDataManager 서브클래스의 추상 훅(LoadTableSetAsync/ValidateForeignKeys/BuildViewSet)을
/// 생성 TableSet/ViewSet 코드의 정적 진입점으로 연결하는 매니저 partial 을 방출한다.
/// </summary>
internal static class ManagerBridgeEmitter
{
    public static string Emit(TableSetGenerator.ManagerAnalysis analysis)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var manager = analysis.ManagerSymbol;
        var scope = GeneratorEmitHelper.OpenNamespaceAndContainingTypes(sb, manager);
        var indent = scope.Indent;

        var tableSetFullyQualifiedName = analysis.TableSetSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        sb.Append(indent).Append("partial class ").AppendLine(GeneratorEmitHelper.EscapeIdentifier(manager.Name));
        sb.Append(indent).AppendLine("{");

        var memberIndent = indent + "    ";

        sb.Append(memberIndent).Append("protected override global::System.Threading.Tasks.Task<")
            .Append(tableSetFullyQualifiedName).AppendLine("> LoadTableSetAsync(");
        sb.Append(memberIndent).AppendLine("    string csvDir,");
        sb.Append(memberIndent).AppendLine("    global::System.Collections.Generic.List<string>? disabledTables,");
        sb.Append(memberIndent).AppendLine("    global::Microsoft.Extensions.Logging.ILogger logger)");
        sb.Append(memberIndent).AppendLine("{");
        sb.Append(memberIndent).Append("    return ").Append(tableSetFullyQualifiedName)
            .AppendLine(".LoadAsync(csvDir, disabledTables, logger);");
        sb.Append(memberIndent).AppendLine("}");
        sb.AppendLine();

        sb.Append(memberIndent).Append("protected override void ValidateForeignKeys(")
            .Append(tableSetFullyQualifiedName).AppendLine(" tableSet)");
        sb.Append(memberIndent).AppendLine("{");
        sb.Append(memberIndent).Append("    ").Append(tableSetFullyQualifiedName)
            .AppendLine(".ValidateForeignKeys(tableSet);");
        sb.Append(memberIndent).AppendLine("}");

        if (analysis.ViewSetSymbol is not null)
        {
            var viewSetFullyQualifiedName = analysis.ViewSetSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            sb.AppendLine();
            sb.Append(memberIndent).Append("protected override ").Append(viewSetFullyQualifiedName)
                .Append(" BuildViewSet(").Append(tableSetFullyQualifiedName)
                .AppendLine(" tableSet, global::Microsoft.Extensions.Logging.ILogger logger)");
            sb.Append(memberIndent).AppendLine("{");
            sb.Append(memberIndent).Append("    return ").Append(viewSetFullyQualifiedName)
                .AppendLine(".Build(tableSet, logger);");
            sb.Append(memberIndent).AppendLine("}");
        }

        sb.Append(indent).AppendLine("}");
        GeneratorEmitHelper.CloseContainingTypes(sb, scope);

        return sb.ToString();
    }
}
