using System.Text;
using Microsoft.CodeAnalysis;

namespace Sdp.SourceGenerator.Generators;

internal static class StaticDataManagerBridgeEmitter
{
    public static string Emit(StaticDataManagerAnalysis analysis)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var staticDataManager = analysis.StaticDataManagerSymbol;
        var scope = EmitHelper.OpenNamespaceAndContainingTypes(sb, staticDataManager);
        var indent = scope.Indent;

        var tableSetFullyQualifiedName = analysis.TableSetSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        sb.Append(indent).Append("partial class ")
            .AppendLine(EmitHelper.EscapeIdentifier(staticDataManager.Name));
        sb.Append(indent).AppendLine("{");

        var memberIndent = indent + "    ";

        sb.Append(memberIndent).Append("protected override global::System.Threading.Tasks.Task<")
            .Append(tableSetFullyQualifiedName).AppendLine("> LoadTableSetAsync(");
        sb.Append(memberIndent).AppendLine("    string csvDir,");
        sb.Append(memberIndent).AppendLine("    global::System.Collections.Generic.List<string>? disabledTables,");
        sb.Append(memberIndent).AppendLine("    global::Microsoft.Extensions.Logging.ILogger logger)");
        sb.Append(memberIndent).AppendLine("{");
        sb.Append(memberIndent).Append("    return ").Append(tableSetFullyQualifiedName)
            .AppendLine(".LoadAsync(csvDir, disabledTables, logger);");
        sb.Append(memberIndent).AppendLine("}");
        sb.AppendLine();

        sb.Append(memberIndent).Append("protected override void ValidateForeignKeys(")
            .Append(tableSetFullyQualifiedName).AppendLine(" tableSet)");
        sb.Append(memberIndent).AppendLine("{");
        sb.Append(memberIndent).Append("    ").Append(tableSetFullyQualifiedName)
            .AppendLine(".ValidateForeignKeys(tableSet);");
        sb.Append(memberIndent).AppendLine("}");

        if (analysis.ViewSetSymbol is not null)
        {
            var viewSetFullyQualifiedName = analysis.ViewSetSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            sb.AppendLine();
            sb.Append(memberIndent).Append("protected override ").Append(viewSetFullyQualifiedName)
                .Append(" BuildViewSet(").Append(tableSetFullyQualifiedName)
                .AppendLine(" tableSet, global::Microsoft.Extensions.Logging.ILogger logger)");
            sb.Append(memberIndent).AppendLine("{");
            sb.Append(memberIndent).Append("    return ").Append(viewSetFullyQualifiedName)
                .AppendLine(".Build(tableSet, logger);");
            sb.Append(memberIndent).AppendLine("}");
        }

        sb.Append(indent).AppendLine("}");
        EmitHelper.CloseContainingTypes(sb, scope);

        return sb.ToString();
    }
}
