using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Sdp.SourceGenerator.Generators;

internal static class StaticDataViewGenerator
{
    public static void Register(IncrementalGeneratorInitializationContext context)
    {
        var views = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateViewClass(node),
                transform: static (syntaxContext, cancellationToken) =>
                    Analyze(syntaxContext, cancellationToken))
            .Where(static analysis => analysis is not null)
            .Collect()
            .SelectMany(static (analyses, _) =>
            {
                var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
                var list = new List<StaticDataViewAnalysis>(analyses.Length);
                foreach (var analysis in analyses)
                {
                    // 같은 View 가 복수 syntax(부분 선언 등)에서 잡혀도 팩토리 셸은 한 번만
                    // 방출하되, 두 번째 이후의 진단은 버리지 않고 진단 전용으로 보존한다.
                    list.Add(seen.Add(analysis!.Symbol)
                        ? analysis
                        : analysis with { CanEmit = false, CanEmitFactoryShell = false });
                }

                return list;
            });

        context.RegisterSourceOutput(views, static (sourceProductionContext, analysis) =>
        {
            foreach (var diagnostic in analysis.Diagnostics)
            {
                sourceProductionContext.ReportDiagnostic(diagnostic);
            }

            if (!analysis.CanEmitFactoryShell)
            {
                return;
            }

            var source = Emit(analysis);
            sourceProductionContext.AddSource(analysis.HintName, source);
        });
    }

    private static bool IsCandidateViewClass(SyntaxNode node)
        => node is ClassDeclarationSyntax classDecl && classDecl.BaseList is not null;

    private static StaticDataViewAnalysis? Analyze(GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var declaredSymbol = context.SemanticModel.GetDeclaredSymbol(classDecl, cancellationToken);
        if (declaredSymbol is not INamedTypeSymbol symbol)
        {
            return null;
        }

        var baseType = StaticDataViewBaseResolver.FindBase(symbol);
        if (baseType is null || baseType.TypeArguments.Length != 2)
        {
            return null;
        }

        var tableSetType = baseType.TypeArguments[1] as INamedTypeSymbol;
        if (tableSetType is null)
        {
            return null;
        }

        var isPartial = classDecl.Modifiers.Any(static modifier => modifier.IsKind(SyntaxKind.PartialKeyword));

        var hasValidCtor = ViewConstructorResolver.HasSingleTableSetConstructor(symbol, tableSetType);

        var diagnostics = new List<Diagnostic>();
        if (!isPartial)
        {
            diagnostics.Add(Diagnostic.Create(
                SdpDiagnostics.StaticDataViewMustBePartial,
                classDecl.Identifier.GetLocation(),
                symbol.ToDisplayString()));
        }

        var containingPartial = ContainingTypePartialChecker.Check(symbol, diagnostics);

        var canEmitFactoryShell = isPartial && containingPartial;
        var canEmit = canEmitFactoryShell && hasValidCtor;

        // 팩토리 셸은 방출 가능하지만 ctor 가 잘못돼 BuildView 가 throw 코드로 떨어지는 경우,
        // throw 메시지가 가리키는 SDP0304 진단을 실제로 보고한다. 이 진단은 모든 view 를 보는
        // StaticDataViewGenerator 가 단일 소유한다(ViewSetGenerator 에서는 보고하지 않음, 중복 방지).
        if (canEmitFactoryShell && !hasValidCtor)
        {
            diagnostics.Add(Diagnostic.Create(
                SdpDiagnostics.StaticDataViewMustHaveTableSetConstructor,
                classDecl.Identifier.GetLocation(),
                symbol.ToDisplayString(),
                tableSetType.ToDisplayString()));
        }

        return new StaticDataViewAnalysis(symbol, tableSetType, diagnostics, canEmit, canEmitFactoryShell);
    }

    private static string Emit(StaticDataViewAnalysis analysis)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var scope = GeneratorEmitHelper.OpenNamespaceAndContainingTypes(sb, analysis.Symbol);
        var indent = scope.Indent;

        var viewFullyQualifiedName = analysis.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var tableSetFullyQualifiedName = analysis.TableSetSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        sb.Append(indent).Append("partial class ").AppendLine(GeneratorEmitHelper.EscapeIdentifier(analysis.Symbol.Name));
        sb.Append(indent).AppendLine("{");

        // 생성 ViewSet 코드가 메서드 그룹으로 ViewSetBuildHelper 에 넘기는 진입점.
        // 같은 어셈블리(소비자)에서만 쓰므로 internal 로 둔다.
        sb.Append(indent).Append("    internal static ").Append(viewFullyQualifiedName)
            .Append(" BuildView(").Append(tableSetFullyQualifiedName).AppendLine(" tableSet)");
        if (analysis.CanEmit)
        {
            sb.Append(indent).AppendLine("    {");
            sb.Append(indent).Append("        var __view = new ").Append(viewFullyQualifiedName).AppendLine("(tableSet);");
            sb.Append(indent).AppendLine("        __view.Validate();");
            sb.Append(indent).AppendLine("        return __view;");
            sb.Append(indent).AppendLine("    }");
        }
        else
        {
            sb.Append(indent).Append("        => throw global::Sdp.View.ViewSetBuildHelper.CannotEmitError(\"")
                .Append(viewFullyQualifiedName).AppendLine("\");");
        }

        sb.Append(indent).AppendLine("}");
        GeneratorEmitHelper.CloseContainingTypes(sb, scope);

        return sb.ToString();
    }
}
