using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace Sdp.SourceGenerator.Generators;

internal static class StaticDataTableEmitter
{
    public static string Emit(StaticDataTableAnalysis analysis)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var scope = GeneratorEmitHelper.OpenNamespaceAndContainingTypes(sb, analysis.Symbol);
        var indent = scope.Indent;

        sb.Append(indent).Append("partial class ").AppendLine(GeneratorEmitHelper.EscapeIdentifier(analysis.TypeName));
        sb.Append(indent).AppendLine("{");

        var memberIndent = indent + "    ";
        if (!analysis.HasUserDefinedConstructor)
        {
            EmitConstructor(sb, analysis, memberIndent);
            sb.AppendLine();
        }

        EmitFactoryMethod(sb, analysis, memberIndent);

        sb.Append(indent).AppendLine("}");
        GeneratorEmitHelper.CloseContainingTypes(sb, scope);

        return sb.ToString();
    }

    private static void EmitConstructor(StringBuilder sb, StaticDataTableAnalysis analysis, string indent)
    {
        sb.Append(indent).Append("public ").Append(GeneratorEmitHelper.EscapeIdentifier(analysis.TypeName)).AppendLine("(");
        sb.Append(indent).Append("    global::System.Collections.Immutable.ImmutableArray<")
            .Append(analysis.FullyQualifiedRecordName).AppendLine("> records)");
        sb.Append(indent).AppendLine("    : base(records)");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).AppendLine("}");
    }

    private static void EmitFactoryMethod(StringBuilder sb, StaticDataTableAnalysis analysis, string indent)
    {
        var fileName = analysis.ExcelFileName + "." + analysis.SheetName + ".csv";
        var fileNameLit = SymbolDisplay.FormatLiteral(fileName, quote: true);

        // 생성 TableSet 코드가 메서드 그룹으로 TableSetLoaderHelper 에 넘기는 진입점.
        // 같은 어셈블리(소비자)에서만 쓰므로 internal 로 둔다.
        sb.Append(indent).Append("internal static async global::System.Threading.Tasks.Task<")
            .Append(analysis.FullyQualifiedTypeName).AppendLine("> LoadAsync(");
        sb.Append(indent).AppendLine("    string csvDir,");
        sb.Append(indent).AppendLine("    global::Microsoft.Extensions.Logging.ILogger logger)");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).Append("    var path = global::System.IO.Path.Combine(csvDir, ").Append(fileNameLit).AppendLine(");");
        sb.Append(indent).Append("    var records = await global::Sdp.Csv.CsvLoader.LoadAsync<")
            .Append(analysis.FullyQualifiedRecordName).Append(">(path, ")
            .Append(analysis.FullyQualifiedRecordName).AppendLine(".MapFromCsvRow);");
        sb.Append(indent).Append("    var __table = new ").Append(analysis.FullyQualifiedTypeName).AppendLine("(records);");
        sb.Append(indent).AppendLine("    __table.Validate();");
        sb.Append(indent).AppendLine("    return __table;");
        sb.Append(indent).AppendLine("}");
    }
}
