using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Sdp.SourceGenerator.Generators;

internal static class TableSetEmitter
{
    public static string Emit(TableSetGenerator.ManagerAnalysis analysis)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var tableSet = analysis.TableSetSymbol;
        var scope = GeneratorEmitHelper.OpenNamespaceAndContainingTypes(sb, tableSet);
        var indent = scope.Indent;

        var tableSetFullyQualifiedName = tableSet.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var recordKeyword = GeneratorEmitHelper.GetTypeKeyword(tableSet);

        sb.Append(indent).Append("partial ").Append(recordKeyword).Append(' ')
            .AppendLine(GeneratorEmitHelper.EscapeIdentifier(tableSet.Name));
        sb.Append(indent).AppendLine("{");

        var memberIndent = indent + "    ";
        EmitLoadAsync(sb, analysis, tableSetFullyQualifiedName, memberIndent);
        sb.AppendLine();
        EmitValidateForeignKeys(sb, analysis, tableSetFullyQualifiedName, memberIndent);

        sb.Append(indent).AppendLine("}");
        GeneratorEmitHelper.CloseContainingTypes(sb, scope);

        return sb.ToString();
    }

    private static void EmitLoadAsync(
        StringBuilder sb,
        TableSetGenerator.ManagerAnalysis analysis,
        string tableSetFullyQualifiedName,
        string indent)
    {
        // SG 가 emit 한 매니저 partial 이 메서드 그룹이 아닌 직접 호출로 연결하는 진입점.
        // 같은 어셈블리(소비자)에서만 쓰므로 internal 로 둔다.
        sb.Append(indent).Append("internal static async global::System.Threading.Tasks.Task<")
            .Append(tableSetFullyQualifiedName).AppendLine("> LoadAsync(");
        sb.Append(indent).AppendLine("    string csvDir,");
        sb.Append(indent).AppendLine("    global::System.Collections.Generic.List<string>? disabledTables,");
        sb.Append(indent).AppendLine("    global::Microsoft.Extensions.Logging.ILogger logger)");
        sb.Append(indent).AppendLine("{");

        for (var i = 0; i < analysis.Tables.Length; i++)
        {
            var table = analysis.Tables[i];
            var fullyQualifiedName = table.TableSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var nameLiteral = SymbolDisplay.FormatLiteral(table.ParameterName, quote: true);
            sb.Append(indent).Append("    var __t").Append(i)
                .Append(" = global::Sdp.Manager.TableSetLoaderHelper.LoadTableOrSkipAsync<")
                .Append(fullyQualifiedName).Append(">(csvDir, disabledTables, ")
                .Append(nameLiteral).Append(", logger, ")
                .Append(fullyQualifiedName).AppendLine(".LoadAsync);");
        }

        sb.AppendLine();
        sb.Append(indent).AppendLine("    try");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).Append("        await global::System.Threading.Tasks.Task.WhenAll(");
        for (var i = 0; i < analysis.Tables.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            sb.Append("__t").Append(i);
        }

        sb.AppendLine(");");
        sb.Append(indent).AppendLine("    }");

        // WhenAll 의 예외는 여기서 삼키고, 각 Task 의 최종 상태를 아래에서 개별 검사해
        // faulted/canceled 를 한 번에 집계한다. (어느 Task 가 실패했는지 모두 모으기 위함)
        sb.Append(indent).AppendLine("    catch (global::System.Exception)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        // Each task's final state is inspected below.");
        sb.Append(indent).AppendLine("    }");
        sb.AppendLine();

        // non-nullable 멤버는 비활성화(disabledTables)될 수 없다. 비활성 테이블은 null 을 돌려주므로,
        // 멤버가 non-nullable 인데 정상 완료 결과가 null 이면 조용히 주입하지 않고 오류로 모은다.
        // 로드 실패와 같은 __errors 채널에 합류시켜 문제를 한 번의 AggregateException 으로 모두 알린다.
        sb.Append(indent).AppendLine("    var __errors = new global::System.Collections.Generic.List<global::System.Exception>();");
        for (var i = 0; i < analysis.Tables.Length; i++)
        {
            sb.Append(indent).Append("    if (__t").Append(i).Append(".IsFaulted) __errors.AddRange(__t").Append(i).AppendLine(".Exception!.InnerExceptions);");
            sb.Append(indent).Append("    else if (__t").Append(i).Append(".IsCanceled) __errors.Add(new global::System.Threading.Tasks.TaskCanceledException(__t").Append(i).AppendLine("));");
            if (!analysis.Tables[i].IsNullable)
            {
                sb.Append(indent).Append("    else if (__t").Append(i)
                    .Append(".Result is null) __errors.Add(global::Sdp.Manager.TableSetLoaderHelper.NonNullableTableDisabledError(")
                    .Append(SymbolDisplay.FormatLiteral(analysis.Tables[i].ParameterName, quote: true)).AppendLine("));");
            }
        }

        sb.Append(indent).AppendLine("    if (__errors.Count > 0)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        throw new global::System.AggregateException(global::Sdp.Manager.TableSetLoaderHelper.TablesFailedToLoadMessage, __errors);");
        sb.Append(indent).AppendLine("    }");
        sb.AppendLine();
        sb.Append(indent).Append("    return new ").Append(tableSetFullyQualifiedName).Append("(");
        for (var i = 0; i < analysis.Tables.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            sb.Append("__t").Append(i).Append(".Result!");
        }

        sb.AppendLine(");");
        sb.Append(indent).AppendLine("}");
    }

    private static void EmitValidateForeignKeys(
        StringBuilder sb,
        TableSetGenerator.ManagerAnalysis analysis,
        string tableSetFullyQualifiedName,
        string indent)
    {
        sb.Append(indent).Append("internal static void ValidateForeignKeys(")
            .Append(tableSetFullyQualifiedName).AppendLine(" tableSet)");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).AppendLine("    var __errors = new global::System.Collections.Generic.List<global::System.Exception>();");

        foreach (var recordFkInfo in analysis.RecordFkInfos)
        {
            var memberAccess = GeneratorEmitHelper.EscapeIdentifier(recordFkInfo.TableSetMember);
            sb.AppendLine();
            sb.Append(indent).Append("    if (tableSet.").Append(memberAccess).AppendLine(" is not null)");
            sb.Append(indent).AppendLine("    {");

            var fkSetVariables = EmitFkTargetSets(sb, recordFkInfo, indent + "        ");

            // '타깃 미로드'는 행과 무관한 테이블 수준 사실이므로 파라미터당 1건만 보고한다.
            // 행 수만큼 동일 오류가 누적되어 AggregateException 이 폭주하는 것을 막는다.
            for (var parameterIndex = 0; parameterIndex < recordFkInfo.Parameters.Length; parameterIndex++)
            {
                sb.Append(indent).Append("        var __fkMissingReported").Append(parameterIndex).AppendLine(" = false;");
            }

            sb.AppendLine();
            for (var parameterIndex = 0; parameterIndex < recordFkInfo.Parameters.Length; parameterIndex++)
            {
                EmitFkTargetsNotLoadedGuard(
                    sb, recordFkInfo.Parameters[parameterIndex], parameterIndex, recordFkInfo, fkSetVariables, indent + "        ");
            }

            sb.AppendLine();
            sb.Append(indent).Append("        foreach (var __r in tableSet.").Append(memberAccess).AppendLine(".Records)");
            sb.Append(indent).AppendLine("        {");

            for (var parameterIndex = 0; parameterIndex < recordFkInfo.Parameters.Length; parameterIndex++)
            {
                EmitFkParameterCheck(sb, recordFkInfo.Parameters[parameterIndex], parameterIndex, recordFkInfo, fkSetVariables, indent + "            ");
            }

            sb.Append(indent).AppendLine("        }");
            sb.Append(indent).AppendLine("    }");
        }

        sb.AppendLine();
        sb.Append(indent).AppendLine("    if (__errors.Count > 0)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        throw new global::System.AggregateException(global::Sdp.Manager.TableSetLoaderHelper.ForeignKeyValidationFailedMessage, __errors);");
        sb.Append(indent).AppendLine("    }");
        sb.Append(indent).AppendLine("}");
    }

    // 레코드마다 타깃 테이블을 선형 탐색하면 O(소스×타깃)이 되므로, 검증에 쓰이는
    // (타깃 멤버, 타깃 컬럼) 조합별 HashSet 을 레코드 루프 진입 전에 한 번만 구축한다.
    // 타깃 테이블이 비활성(null)이면 set 도 null 로 남겨 '타깃 미로드' 판정에 그대로 쓴다.
    private static Dictionary<string, string> EmitFkTargetSets(
        StringBuilder sb,
        TableSetGenerator.RecordFkInfo recordFkInfo,
        string indent)
    {
        var setVariables = new Dictionary<string, string>(System.StringComparer.Ordinal);

        foreach (var fkParameter in recordFkInfo.Parameters)
        {
            var propertyTypeFullyQualifiedName = fkParameter.PropertyType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            foreach (var branch in fkParameter.Branches)
            {
                var setKey = FkSetKey(branch, propertyTypeFullyQualifiedName);
                if (setVariables.ContainsKey(setKey))
                {
                    continue;
                }

                var setVariable = "__fkSet" + setVariables.Count.ToString(System.Globalization.CultureInfo.InvariantCulture);
                setVariables[setKey] = setVariable;

                var targetMemberAccess = GeneratorEmitHelper.EscapeIdentifier(branch.TableSetMember);
                sb.Append(indent).Append("global::System.Collections.Generic.HashSet<").Append(propertyTypeFullyQualifiedName)
                    .Append(">? ").Append(setVariable).AppendLine(" = null;");
                sb.Append(indent).Append("if (tableSet.").Append(targetMemberAccess).AppendLine(" is not null)");
                sb.Append(indent).AppendLine("{");
                sb.Append(indent).Append("    ").Append(setVariable)
                    .Append(" = new global::System.Collections.Generic.HashSet<").Append(propertyTypeFullyQualifiedName).AppendLine(">();");
                sb.Append(indent).Append("    foreach (var __t in tableSet.").Append(targetMemberAccess).AppendLine(".Records)");
                sb.Append(indent).AppendLine("    {");
                sb.Append(indent).Append("        ").Append(setVariable).Append(".Add(__t.")
                    .Append(GeneratorEmitHelper.EscapeIdentifier(branch.TargetColumn)).AppendLine(");");
                sb.Append(indent).AppendLine("    }");
                sb.Append(indent).AppendLine("}");
                sb.AppendLine();
            }
        }

        return setVariables;
    }

    private static string FkSetKey(TableSetGenerator.FkBranch branch, string propertyTypeFullyQualifiedName)
    {
        return branch.TableSetMember + "\0" + branch.TargetColumn + "\0" + propertyTypeFullyQualifiedName;
    }

    // '타깃 미로드'(disabledTables 구성 오류)는 행과 무관한 사실이므로, 행 루프에 들어가기 전에
    // 파라미터의 모든 타깃 set 이 null 이면 즉시 1건 보고한다. 소스 테이블이 비어 있거나 nullable FK 가
    // 전부 null 이어도 구성 오류가 잠복하지 않는다(구 ReferenceValidator 의 스키마 단계 판정과 동일).
    // 일부 타깃만 비활성인 경우는 행 루프의 기존 판정에 맡긴다.
    private static void EmitFkTargetsNotLoadedGuard(
        StringBuilder sb,
        TableSetGenerator.FkParameter fkParameter,
        int parameterIndex,
        TableSetGenerator.RecordFkInfo recordFkInfo,
        Dictionary<string, string> fkSetVariables,
        string indent)
    {
        var propertyTypeFullyQualifiedName = fkParameter.PropertyType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var setVariables = fkParameter.Branches
            .Select(branch => fkSetVariables[FkSetKey(branch, propertyTypeFullyQualifiedName)])
            .Distinct()
            .ToList();
        var condition = string.Join(" && ", setVariables.Select(setVariable => setVariable + " is null"));
        var missingReportedVariable = "__fkMissingReported" + parameterIndex.ToString(System.Globalization.CultureInfo.InvariantCulture);
        var sourceLiteral = SymbolDisplay.FormatLiteral(
            recordFkInfo.RecordSymbol.Name + "." + fkParameter.PropertyName, quote: true);
        var targetMembers = string.Join(", ", fkParameter.Branches.Select(branch => branch.TableSetMember).Distinct());
        var targetLiteral = SymbolDisplay.FormatLiteral(targetMembers, quote: true);

        sb.Append(indent).Append("if (").Append(condition).AppendLine(")");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).Append("    ").Append(missingReportedVariable).AppendLine(" = true;");
        sb.Append(indent).Append("    __errors.Add(global::Sdp.Manager.TableSetLoaderHelper.FkTargetNotLoadedError(")
            .Append(sourceLiteral).Append(", ").Append(targetLiteral).AppendLine("));");
        sb.Append(indent).AppendLine("}");
    }

    private static void EmitFkParameterCheck(
        StringBuilder sb,
        TableSetGenerator.FkParameter fkParameter,
        int parameterIndex,
        TableSetGenerator.RecordFkInfo recordFkInfo,
        Dictionary<string, string> fkSetVariables,
        string indent)
    {
        var propertyTypeFullyQualifiedName = fkParameter.PropertyType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var keyParameter = FindKeyParameter(recordFkInfo.RecordSymbol);
        var keyClause = keyParameter is null
            ? string.Empty
            : "[" + keyParameter.Name + "=" + BuildKeyValueAccess(keyParameter) + "]";

        // 오류 팩토리(TableSetLoaderHelper)에 넘길 인자 식.
        // recordDisplayExpr 는 키 값 보간이 들어가면 Invariant($"...") 식, 아니면 리터럴이다.
        var recordDisplayExpr = keyClause.Length == 0
            ? SymbolDisplay.FormatLiteral(recordFkInfo.RecordSymbol.Name, quote: true)
            : "global::System.FormattableString.Invariant($\"" + recordFkInfo.RecordSymbol.Name + keyClause + "\")";
        var propertyNameLiteral = SymbolDisplay.FormatLiteral(fkParameter.PropertyName, quote: true);
        var sourceLiteral = SymbolDisplay.FormatLiteral(
            recordFkInfo.RecordSymbol.Name + "." + fkParameter.PropertyName, quote: true);
        var missingReportedVariable = "__fkMissingReported" + parameterIndex.ToString(System.Globalization.CultureInfo.InvariantCulture);

        // nullable FK 가 null 이면 "참조 없음"이므로 모든 FK/SwitchFK 검사를 건너뛴다.
        var isNullable = TypeClassifier.IsNullable(fkParameter.PropertyType);

        sb.Append(indent).AppendLine("{");
        sb.Append(indent).Append("    var __v = __r.")
            .Append(GeneratorEmitHelper.EscapeIdentifier(fkParameter.PropertyName)).AppendLine(";");

        var body = indent;
        if (isNullable)
        {
            sb.Append(indent).AppendLine("    if (__v is not null)");
            sb.Append(indent).AppendLine("    {");
            body = indent + "    ";
        }

        sb.Append(body).AppendLine("    var __ok = false;");

        var fkBranches = new List<TableSetGenerator.FkBranch>();
        var switchBranches = new List<TableSetGenerator.FkBranch>();
        foreach (var branch in fkParameter.Branches)
        {
            if (branch.IsSwitch)
            {
                switchBranches.Add(branch);
            }
            else
            {
                fkBranches.Add(branch);
            }
        }

        // '타깃 미로드' 오류를 파라미터당 1건으로 막는 가드를 방출한다. 판정은 행과 무관하다.
        void AppendTargetNotLoadedError(string lineIndent, string targetMembers)
        {
            var targetLiteral = SymbolDisplay.FormatLiteral(targetMembers, quote: true);
            sb.Append(lineIndent).Append("if (!").Append(missingReportedVariable).AppendLine(")");
            sb.Append(lineIndent).AppendLine("{");
            sb.Append(lineIndent).Append("    ").Append(missingReportedVariable).AppendLine(" = true;");
            sb.Append(lineIndent).Append("    __errors.Add(global::Sdp.Manager.TableSetLoaderHelper.FkTargetNotLoadedError(")
                .Append(sourceLiteral).Append(", ").Append(targetLiteral).AppendLine("));");
            sb.Append(lineIndent).AppendLine("}");
        }

        // 'FK 값 미일치' 오류를 방출한다. valueExpr 는 보간 홀을 포함한 문자열 본문이다.
        void AppendValueNotFoundError(string lineIndent, string valueBody, string targets)
        {
            var targetsLiteral = SymbolDisplay.FormatLiteral(targets, quote: true);
            sb.Append(lineIndent).Append("__errors.Add(global::Sdp.Manager.TableSetLoaderHelper.FkValueNotFoundError(")
                .AppendLine();
            sb.Append(lineIndent).Append("    ").Append(recordDisplayExpr).Append(", ").Append(propertyNameLiteral).AppendLine(",");
            sb.Append(lineIndent).Append("    global::System.FormattableString.Invariant($\"").Append(valueBody).Append("\"), ")
                .Append(targetsLiteral).AppendLine("));");
        }

        if (fkBranches.Count > 0)
        {
            sb.Append(body).AppendLine("    var __targetLoaded = false;");
            foreach (var branch in fkBranches)
            {
                var setVariable = fkSetVariables[FkSetKey(branch, propertyTypeFullyQualifiedName)];
                sb.Append(body).Append("    if (").Append(setVariable).AppendLine(" is not null)");
                sb.Append(body).AppendLine("    {");
                sb.Append(body).AppendLine("        __targetLoaded = true;");
                sb.Append(body).Append("        if (!__ok && ").Append(setVariable).AppendLine(".Contains(__v))");
                sb.Append(body).AppendLine("        {");
                sb.Append(body).AppendLine("            __ok = true;");
                sb.Append(body).AppendLine("        }");
                sb.Append(body).AppendLine("    }");
            }

            var fkTargetMembers = string.Join(", ", fkBranches.Select(branch => branch.TableSetMember).Distinct());
            var fkTargets = string.Join(", ", fkBranches.Select(branch => branch.TableSetMember + "." + branch.TargetColumn).Distinct());

            sb.Append(body).AppendLine("    if (!__ok)");
            sb.Append(body).AppendLine("    {");
            sb.Append(body).AppendLine("        if (!__targetLoaded)");
            sb.Append(body).AppendLine("        {");
            AppendTargetNotLoadedError(body + "            ", fkTargetMembers);
            sb.Append(body).AppendLine("        }");
            sb.Append(body).AppendLine("        else");
            sb.Append(body).AppendLine("        {");
            AppendValueNotFoundError(body + "            ", "{__v}", fkTargets);
            sb.Append(body).AppendLine("        }");
            sb.Append(body).AppendLine("    }");
        }

        if (switchBranches.Count > 0)
        {
            var conditionColumn = switchBranches[0].ConditionColumn!;
            var conditionColumnAccess = GeneratorEmitHelper.EscapeIdentifier(conditionColumn);

            // 조건 프로퍼티 타입은 분석 측(CollectFkParameters)이 해석해 FkBranch 에 담아 준다. 재조회하지 않는다.
            var conditionPropertyType = switchBranches[0].ConditionType!;
            var conditionType = TypeClassifier.UnwrapNullable(conditionPropertyType);

            // ToString 문자열 왕복 대신 조건 컬럼 값을 직접 비교한다(culture 함정 제거 + 행 단위 할당 제거).
            // 타입 비교를 구성할 수 없는 종류([Flags] enum 조합값, 커스텀 타입 등)는 기존 ToString 비교로 폴백한다.
            var typedLiterals = TryBuildTypedConditionLiterals(conditionType, switchBranches);

            if (typedLiterals is null)
            {
                var useInvariant = IsFormattable(conditionPropertyType);
                var isNonNullableValue = conditionPropertyType.IsValueType
                    && conditionPropertyType.NullableAnnotation != NullableAnnotation.Annotated;
                var conditionalOperator = isNonNullableValue ? "." : "?.";

                // IFormattable 은 단일 인자 ToString(IFormatProvider) 오버로드를 보장하지 않는다
                // (TimeSpan/Guid 등에는 없음). 인터페이스가 보장하는 2-인자 오버로드를 캐스트 경유로 호출한다.
                string conditionInitializer;
                if (useInvariant)
                {
                    var castType = isNonNullableValue ? "global::System.IFormattable" : "global::System.IFormattable?";
                    conditionInitializer = "((" + castType + ")__r." + conditionColumnAccess + ")" + conditionalOperator
                        + "ToString(null, global::System.Globalization.CultureInfo.InvariantCulture)";
                }
                else
                {
                    conditionInitializer = "__r." + conditionColumnAccess + conditionalOperator + "ToString()";
                }

                sb.Append(body).Append("    var __cond = ").Append(conditionInitializer).AppendLine(";");
            }

            sb.Append(body).AppendLine("    var __matched = false;");
            sb.Append(body).AppendLine("    var __switchTargetLoaded = false;");

            var conditionDisplay = typedLiterals is not null ? "{__r." + conditionColumnAccess + "}" : "{__cond}";
            var conditionSuffix = " (when " + conditionColumn + "=" + conditionDisplay + ")";

            for (var branchIndex = 0; branchIndex < switchBranches.Count; branchIndex++)
            {
                var branch = switchBranches[branchIndex];
                var conditionExpression = typedLiterals is not null
                    ? "__r." + conditionColumnAccess + " == " + typedLiterals[branchIndex]
                    : "__cond == " + SymbolDisplay.FormatLiteral(branch.ConditionValue!, quote: true);

                var setVariable = fkSetVariables[FkSetKey(branch, propertyTypeFullyQualifiedName)];
                sb.Append(body).Append("    if (!__matched && ").Append(conditionExpression).AppendLine(")");
                sb.Append(body).AppendLine("    {");
                sb.Append(body).AppendLine("        __matched = true;");
                sb.Append(body).Append("        if (").Append(setVariable).AppendLine(" is not null)");
                sb.Append(body).AppendLine("        {");
                sb.Append(body).AppendLine("            __switchTargetLoaded = true;");
                sb.Append(body).Append("            if (").Append(setVariable).AppendLine(".Contains(__v))");
                sb.Append(body).AppendLine("            {");
                sb.Append(body).AppendLine("                __ok = true;");
                sb.Append(body).AppendLine("            }");
                sb.Append(body).AppendLine("            else");
                sb.Append(body).AppendLine("            {");

                // 값 미일치 메시지에는 실제로 검사한(조건이 매칭된) 분기의 타깃만 표기한다.
                // 다른 분기의 타깃은 검사된 적이 없으므로 나열하면 거짓 정보가 된다.
                AppendValueNotFoundError(
                    body + "                ",
                    "{__v}" + conditionSuffix,
                    branch.TableSetMember + "." + branch.TargetColumn);
                sb.Append(body).AppendLine("            }");
                sb.Append(body).AppendLine("        }");
                sb.Append(body).AppendLine("    }");
            }

            var conditionColumnLiteral = SymbolDisplay.FormatLiteral(conditionColumn, quote: true);
            var switchTargetMembers = string.Join(", ", switchBranches.Select(branch => branch.TableSetMember).Distinct());

            sb.Append(body).AppendLine("    if (!__matched)");
            sb.Append(body).AppendLine("    {");
            sb.Append(body).AppendLine("        __errors.Add(global::Sdp.Manager.TableSetLoaderHelper.SwitchFkConditionNotMatchedError(");
            sb.Append(body).Append("            ").Append(recordDisplayExpr).Append(", ").Append(propertyNameLiteral).AppendLine(",");
            sb.Append(body).Append("            ").Append(conditionColumnLiteral)
                .Append(", global::System.FormattableString.Invariant($\"").Append(conditionDisplay).AppendLine("\")));");
            sb.Append(body).AppendLine("    }");
            sb.Append(body).AppendLine("    else if (!__ok && !__switchTargetLoaded)");
            sb.Append(body).AppendLine("    {");
            AppendTargetNotLoadedError(body + "        ", switchTargetMembers);
            sb.Append(body).AppendLine("    }");
        }

        if (isNullable)
        {
            sb.Append(indent).AppendLine("    }");
        }

        sb.Append(indent).AppendLine("}");
    }

    private static IParameterSymbol? FindKeyParameter(INamedTypeSymbol record)
    {
        // 다른 분석 경로와 동일하게 primary constructor 의 파라미터만 본다. 보조 생성자의
        // 파라미터는 대응 프로퍼티가 없어 __r.{이름} 접근이 생성 코드에서 CS1061 이 된다.
        var primaryConstructor = SinglePrimaryConstructorResolver.Resolve(record);
        if (primaryConstructor is null)
        {
            return null;
        }

        foreach (var param in primaryConstructor.Parameters)
        {
            foreach (var attr in param.GetAttributes())
            {
                if (attr.AttributeClass?.Name == "KeyAttribute"
                    && attr.AttributeClass.ContainingNamespace?.ToDisplayString() == "Sdp.Attributes")
                {
                    return param;
                }
            }
        }

        return null;
    }

    // FK 오류 메시지에 넣을 키 값 보간식을 만든다. 키가 강타입 래퍼(단일 파라미터를 가진 value-type record,
    // 예: record struct Identifier(int Value))이면 그 멤버까지 풀어 메시지에 원시 값이 찍히게 한다.
    private static string BuildKeyValueAccess(IParameterSymbol keyParameter)
    {
        var access = "__r." + GeneratorEmitHelper.EscapeIdentifier(keyParameter.Name);
        if (keyParameter.Type is INamedTypeSymbol { IsValueType: true, IsRecord: true } keyType)
        {
            var primaryConstructor = SinglePrimaryConstructorResolver.Resolve(keyType);
            if (primaryConstructor is { Parameters.Length: 1 })
            {
                access += "." + GeneratorEmitHelper.EscapeIdentifier(primaryConstructor.Parameters[0].Name);
            }
        }

        return "{" + access + "}";
    }

    private static bool IsFormattable(ITypeSymbol type)
    {
        var underlying = TypeClassifier.UnwrapNullable(type);

        if (underlying.TypeKind == TypeKind.Enum)
        {
            return false;
        }

        return underlying.AllInterfaces.Any(i =>
            i.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.IFormattable");
    }

    // 모든 분기의 ConditionValue 를 조건 컬럼 타입의 리터럴로 만들 수 있으면 그 리스트를, 하나라도 불가하면 null 을 반환한다.
    private static List<string>? TryBuildTypedConditionLiterals(
        ITypeSymbol? conditionType,
        List<TableSetGenerator.FkBranch> switchBranches)
    {
        if (conditionType is null)
        {
            return null;
        }

        var literals = new List<string>(switchBranches.Count);
        foreach (var branch in switchBranches)
        {
            if (branch.ConditionValue is not { } value)
            {
                return null;
            }

            var literal = BuildTypedConditionLiteral(conditionType, value);
            if (literal is null)
            {
                return null;
            }

            literals.Add(literal);
        }

        return literals;
    }

    private static string? BuildTypedConditionLiteral(ITypeSymbol conditionType, string conditionValue)
    {
        if (conditionType.TypeKind == TypeKind.Enum && conditionType is INamedTypeSymbol enumType)
        {
            // [Flags] enum 의 조합값('A, B')은 단일 멤버/숫자로 표현할 수 없어 폴백한다.
            if (TableSetGenerator.HasFlagsAttribute(enumType))
            {
                return null;
            }

            var enumFullyQualifiedName = enumType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            foreach (var member in enumType.GetMembers().OfType<IFieldSymbol>())
            {
                if (member.IsConst && string.Equals(member.Name, conditionValue, System.StringComparison.Ordinal))
                {
                    return enumFullyQualifiedName + "." + GeneratorEmitHelper.EscapeIdentifier(member.Name);
                }
            }

            // 멤버명이 아니면 미정의 숫자값으로 보고 캐스트 비교한다(원본 Enum 동작 보존).
            // underlying 타입 범위를 벗어난 값은 상수 캐스트가 생성 코드에서 CS0221 이 되므로
            // 폴백(ToString 비교)으로 돌린다 — 그 값은 어차피 어떤 행과도 매칭될 수 없다.
            if (long.TryParse(
                    conditionValue,
                    System.Globalization.NumberStyles.Integer,
                    System.Globalization.CultureInfo.InvariantCulture,
                    out var enumNumeric)
                && TableSetGenerator.FitsInEnumUnderlyingType(enumType, enumNumeric))
            {
                return "(" + enumFullyQualifiedName + ")(" + enumNumeric.ToString(System.Globalization.CultureInfo.InvariantCulture) + ")";
            }

            return null;
        }

        switch (conditionType.SpecialType)
        {
            case SpecialType.System_String:
                return SymbolDisplay.FormatLiteral(conditionValue, quote: true);

            case SpecialType.System_Char:
                return conditionValue.Length == 1
                    ? SymbolDisplay.FormatLiteral(conditionValue[0], quote: true)
                    : null;

            case SpecialType.System_Boolean:
                return bool.TryParse(conditionValue, out var boolValue)
                    ? (boolValue ? "true" : "false")
                    : null;

            case SpecialType.System_Byte:
            case SpecialType.System_SByte:
            case SpecialType.System_Int16:
            case SpecialType.System_UInt16:
            case SpecialType.System_Int32:
            case SpecialType.System_UInt32:
            case SpecialType.System_Int64:
                // 컬럼 타입 범위를 벗어난 상수 비교는 생성 코드에서 CS0652 가 되므로
                // 폴백(ToString 비교)으로 돌린다 — 그 값은 어차피 어떤 행과도 매칭될 수 없다.
                return long.TryParse(
                        conditionValue,
                        System.Globalization.NumberStyles.Integer,
                        System.Globalization.CultureInfo.InvariantCulture,
                        out var signed)
                    && TableSetGenerator.FitsInIntegralType(conditionType.SpecialType, signed)
                    ? signed.ToString(System.Globalization.CultureInfo.InvariantCulture)
                    : null;

            case SpecialType.System_UInt64:
                return ulong.TryParse(
                        conditionValue,
                        System.Globalization.NumberStyles.Integer,
                        System.Globalization.CultureInfo.InvariantCulture,
                        out var unsigned)
                    ? unsigned.ToString(System.Globalization.CultureInfo.InvariantCulture)
                    : null;

            default:
                return null;
        }
    }
}
