using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Sdp.SourceGenerator.Generators;

internal static partial class TableSetEmitter
{
    public static string Emit(StaticDataManagerAnalysis analysis)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var tableSet = analysis.TableSetSymbol;
        var scope = EmitHelper.OpenNamespaceAndContainingTypes(sb, tableSet);
        var indent = scope.Indent;

        var tableSetFullyQualifiedName = tableSet.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var recordKeyword = EmitHelper.GetTypeKeyword(tableSet);
        sb.Append(indent).Append("partial ").Append(recordKeyword).Append(' ')
            .AppendLine(EmitHelper.EscapeIdentifier(tableSet.Name));
        sb.Append(indent).AppendLine("{");

        var memberIndent = indent + "    ";
        EmitLoadAsync(sb, analysis, tableSetFullyQualifiedName, memberIndent);
        sb.AppendLine();
        EmitValidateForeignKeys(sb, analysis, tableSetFullyQualifiedName, memberIndent);

        sb.Append(indent).AppendLine("}");
        EmitHelper.CloseContainingTypes(sb, scope);

        return sb.ToString();
    }

    private static void EmitLoadAsync(
        StringBuilder sb,
        StaticDataManagerAnalysis analysis,
        string tableSetFullyQualifiedName,
        string indent)
    {
        sb.Append(indent).Append("internal static async global::System.Threading.Tasks.Task<")
            .Append(tableSetFullyQualifiedName).AppendLine("> LoadAsync(");
        sb.Append(indent).AppendLine("    string csvDir,");
        sb.Append(indent).AppendLine("    global::System.Collections.Generic.List<string>? disabledTables,");
        sb.Append(indent).AppendLine("    global::Microsoft.Extensions.Logging.ILogger logger)");
        sb.Append(indent).AppendLine("{");

        for (var i = 0; i < analysis.Tables.Length; i++)
        {
            var table = analysis.Tables[i];
            var fullyQualifiedName = table.TableSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var nameLiteral = SymbolDisplay.FormatLiteral(table.ParameterName, quote: true);
            sb.Append(indent).Append("    var __t").Append(i)
                .Append(" = global::Sdp.Manager.TableSetLoaderHelper.LoadTableOrSkipAsync<")
                .Append(fullyQualifiedName).Append(">(csvDir, ")
                .Append(nameLiteral).Append(", disabledTables, ")
                .Append(fullyQualifiedName).AppendLine(".LoadAsync, logger);");
        }

        sb.AppendLine();
        sb.Append(indent).AppendLine("    try");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).Append("        await global::System.Threading.Tasks.Task.WhenAll(");
        for (var i = 0; i < analysis.Tables.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            sb.Append("__t").Append(i);
        }

        sb.AppendLine(");");
        sb.Append(indent).AppendLine("    }");

        sb.Append(indent).AppendLine("    catch (global::System.Exception)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("    }");
        sb.AppendLine();

        sb.Append(indent).AppendLine("    var __errors = new global::System.Collections.Generic.List<global::System.Exception>();");
        for (var i = 0; i < analysis.Tables.Length; i++)
        {
            sb.Append(indent).Append("    if (__t").Append(i).Append(".IsFaulted) __errors.AddRange(__t").Append(i).AppendLine(".Exception!.InnerExceptions);");
            sb.Append(indent).Append("    else if (__t").Append(i).Append(".IsCanceled) __errors.Add(new global::System.Threading.Tasks.TaskCanceledException(__t").Append(i).AppendLine("));");
            if (!analysis.Tables[i].IsNullable)
            {
                sb.Append(indent).Append("    else if (__t").Append(i)
                    .Append(".Result is null) __errors.Add(global::Sdp.Manager.TableSetLoaderHelper.NonNullableTableDisabledError(")
                    .Append(SymbolDisplay.FormatLiteral(analysis.Tables[i].ParameterName, quote: true)).AppendLine("));");
            }
        }

        sb.Append(indent).AppendLine("    if (__errors.Count > 0)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        throw new global::System.AggregateException(global::Sdp.Manager.TableSetLoaderHelper.TablesFailedToLoadMessage, __errors);");
        sb.Append(indent).AppendLine("    }");
        sb.AppendLine();
        sb.Append(indent).Append("    return new ").Append(tableSetFullyQualifiedName).Append("(");
        for (var i = 0; i < analysis.Tables.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            sb.Append("__t").Append(i).Append(".Result!");
        }

        sb.AppendLine(");");
        sb.Append(indent).AppendLine("}");
    }
}
