using System.Text;
using Microsoft.CodeAnalysis;

namespace Sdp.SourceGenerator.Generators;

internal static class ViewSetEmitter
{
    public static string Emit(ViewSetGenerator.ViewSetAnalysis analysis)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var viewSet = analysis.ViewSetSymbol;
        var scope = GeneratorEmitHelper.OpenNamespaceAndContainingTypes(sb, viewSet);
        var indent = scope.Indent;

        var viewSetFullyQualifiedName = viewSet.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var tableSetFullyQualifiedName = analysis.TableSetSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        sb.Append(indent).Append("partial ").Append(GeneratorEmitHelper.GetTypeKeyword(viewSet)).Append(' ')
            .AppendLine(GeneratorEmitHelper.EscapeIdentifier(viewSet.Name));
        sb.Append(indent).AppendLine("{");

        if (analysis.CanEmit)
        {
            EmitBuild(sb, analysis, viewSetFullyQualifiedName, tableSetFullyQualifiedName, indent + "    ");
        }
        else if (HasDeferrableErrors(analysis))
        {
            EmitDeferredErrorBuild(sb, analysis, viewSetFullyQualifiedName, tableSetFullyQualifiedName, indent + "    ");
        }
        else
        {
            EmitNotSupportedShell(sb, viewSetFullyQualifiedName, tableSetFullyQualifiedName, indent + "    ");
        }

        sb.Append(indent).AppendLine("}");
        GeneratorEmitHelper.CloseContainingTypes(sb, scope);

        return sb.ToString();
    }

    // 구조적으로 잘못된 ViewSet (멤버가 View 아님 / nullable / TableSet 생성자 없음)에 대해서는,
    // SDP03xx 진단을 사용자가 억제하더라도 런타임에 반드시 실패하도록 지역화된 예외를 던지는 Build 를 방출한다.
    // analyzer 설정에 의존하지 않고 동작을 보장하기 위함이다.
    private static bool HasDeferrableErrors(ViewSetGenerator.ViewSetAnalysis analysis)
    {
        foreach (var view in analysis.Views)
        {
            if (!view.IsFullyValid)
            {
                return true;
            }
        }

        return false;
    }

    private static void EmitDeferredErrorBuild(
        StringBuilder sb,
        ViewSetGenerator.ViewSetAnalysis analysis,
        string viewSetFullyQualifiedName,
        string tableSetFullyQualifiedName,
        string indent)
    {
        // 같은 메시지에 들어가는 View 쪽 TableSet(ViewTableSetName)과 컴파일 타임 진단(SDP0304/0308)이
        // 모두 네임스페이스 포함 표기를 쓰므로 동일하게 맞춘다.
        var tableSetName = analysis.TableSetSymbol.ToDisplayString();

        sb.Append(indent).Append("internal static ").Append(viewSetFullyQualifiedName).AppendLine(" Build(");
        sb.Append(indent).Append("    ").Append(tableSetFullyQualifiedName).AppendLine(" tableSet,");
        sb.Append(indent).AppendLine("    global::Microsoft.Extensions.Logging.ILogger logger)");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).AppendLine("    var __errors = new global::System.Collections.Generic.List<global::System.Exception>();");

        foreach (var view in analysis.Views)
        {
            if (!view.IsView)
            {
                sb.Append(indent).Append("    __errors.Add(global::Sdp.View.ViewSetBuildHelper.InvalidViewParameterError(")
                    .Append(Literal(view.ParameterName)).Append(", ").Append(Literal(view.TypeName)).AppendLine("));");
                continue;
            }

            if (view.IsNullable)
            {
                sb.Append(indent).Append("    __errors.Add(global::Sdp.View.ViewSetBuildHelper.NullableViewMemberError(")
                    .Append(Literal(view.ParameterName)).Append(", ").Append(Literal(view.TypeName)).AppendLine("));");
            }

            // View 가 다른 TableSet 을 대상으로 하면 매니저 TableSet 기준의 생성자 검사(HasValidCtor)는
            // 오답을 가리키므로, 대상 불일치 오류만 보고하고 생성자 오류는 보고하지 않는다.
            if (!view.TargetsManagerTableSet)
            {
                sb.Append(indent).Append("    __errors.Add(global::Sdp.View.ViewSetBuildHelper.ViewTargetsDifferentTableSetError(")
                    .Append(Literal(view.TypeName)).Append(", ").Append(Literal(view.ViewTableSetName ?? string.Empty))
                    .Append(", ").Append(Literal(tableSetName)).AppendLine("));");
            }
            else if (!view.HasValidCtor)
            {
                sb.Append(indent).Append("    __errors.Add(global::Sdp.View.ViewSetBuildHelper.ViewConstructorNotFoundError(")
                    .Append(Literal(view.TypeName)).Append(", ").Append(Literal(tableSetName)).AppendLine("));");
            }

            if (!view.IsPartial)
            {
                sb.Append(indent).Append("    __errors.Add(global::Sdp.View.ViewSetBuildHelper.ViewNotPartialError(")
                    .Append(Literal(view.TypeName)).AppendLine("));");
            }

            if (!view.ContainingTypesPartial)
            {
                sb.Append(indent).Append("    __errors.Add(global::Sdp.View.ViewSetBuildHelper.ViewContainingTypeNotPartialError(")
                    .Append(Literal(view.TypeName)).AppendLine("));");
            }
        }

        sb.Append(indent).AppendLine("    throw new global::System.AggregateException(global::Sdp.View.ViewSetBuildHelper.ViewsFailedToBuildMessage, __errors);");
        sb.Append(indent).AppendLine("}");
    }

    private static string Literal(string value)
        => Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, true);

    private static void EmitNotSupportedShell(
        StringBuilder sb,
        string viewSetFullyQualifiedName,
        string tableSetFullyQualifiedName,
        string indent)
    {
        sb.Append(indent).Append("internal static ").Append(viewSetFullyQualifiedName).AppendLine(" Build(");
        sb.Append(indent).Append("    ").Append(tableSetFullyQualifiedName).AppendLine(" tableSet,");
        sb.Append(indent).AppendLine("    global::Microsoft.Extensions.Logging.ILogger logger)");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).Append("    throw new global::System.NotSupportedException(\"Sdp.SourceGenerator: ViewSet '")
            .Append(viewSetFullyQualifiedName).Append(GeneratorEmitHelper.CannotEmitDiagnosticSuffix).AppendLine("\");");
        sb.Append(indent).AppendLine("}");
    }

    private static void EmitBuild(
        StringBuilder sb,
        ViewSetGenerator.ViewSetAnalysis analysis,
        string viewSetFullyQualifiedName,
        string tableSetFullyQualifiedName,
        string indent)
    {
        // SG 가 emit 한 매니저 partial 이 직접 호출로 연결하는 진입점.
        // 같은 어셈블리(소비자)에서만 쓰므로 internal 로 둔다.
        sb.Append(indent).Append("internal static ").Append(viewSetFullyQualifiedName).AppendLine(" Build(");
        sb.Append(indent).Append("    ").Append(tableSetFullyQualifiedName).AppendLine(" tableSet,");
        sb.Append(indent).AppendLine("    global::Microsoft.Extensions.Logging.ILogger logger)");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).AppendLine("    var __errors = new global::System.Collections.Generic.List<global::System.Exception>();");
        sb.AppendLine();

        for (var i = 0; i < analysis.Views.Length; i++)
        {
            var view = analysis.Views[i];
            var viewFullyQualifiedName = view.ViewSymbol!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.Append(indent).Append("    ").Append(viewFullyQualifiedName).Append(" __v").Append(i).AppendLine(" = null!;");
            sb.Append(indent).AppendLine("    try");
            sb.Append(indent).AppendLine("    {");
            sb.Append(indent).Append("        __v").Append(i)
                .Append(" = global::Sdp.View.ViewSetBuildHelper.Build<")
                .Append(viewFullyQualifiedName).Append(", ").Append(tableSetFullyQualifiedName).Append(">(tableSet, ")
                .Append(Literal(view.ParameterName)).Append(", logger, ")
                .Append(viewFullyQualifiedName).AppendLine(".BuildView);");
            sb.Append(indent).AppendLine("    }");
            sb.Append(indent).AppendLine("    catch (global::System.Exception ex)");
            sb.Append(indent).AppendLine("    {");
            sb.Append(indent).AppendLine("        __errors.Add(ex);");
            sb.Append(indent).AppendLine("    }");
            sb.AppendLine();
        }

        sb.Append(indent).AppendLine("    if (__errors.Count > 0)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        throw new global::System.AggregateException(global::Sdp.View.ViewSetBuildHelper.ViewsFailedToBuildMessage, __errors);");
        sb.Append(indent).AppendLine("    }");
        sb.AppendLine();

        sb.Append(indent).Append("    return new ").Append(viewSetFullyQualifiedName).Append("(");
        for (var i = 0; i < analysis.Views.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            sb.Append("__v").Append(i);
        }

        sb.AppendLine(");");
        sb.Append(indent).AppendLine("}");
    }
}
