// <auto-generated/>
// This file is manually maintained to match Messages.resx.
// Update this file when Messages.resx changes.
#nullable enable

namespace StaticDataHeaderGenerator.Resources;

using System.Globalization;
using System.Resources;
using System.Text;

internal static class Messages
{
    private static ResourceManager? resourceMan;

    internal static ResourceManager ResourceManager
    {
        get
        {
            resourceMan ??= new ResourceManager("StaticDataHeaderGenerator.Resources.Messages", typeof(Messages).Assembly);
            return resourceMan;
        }
    }

    internal static CultureInfo? Culture { get; set; }

    internal static string GeneratingHeaderFile
        => ResourceManager.GetString("GeneratingHeaderFile", Culture)!;

    internal static string HeadersGenerated
        => ResourceManager.GetString("HeadersGenerated", Culture)!;

    internal static string HeaderFileSaved
        => ResourceManager.GetString("HeaderFileSaved", Culture)!;

    internal static string RecordNameNotFound
        => ResourceManager.GetString("RecordNameNotFound", Culture)!;

    internal static string NoRecordsFound
        => ResourceManager.GetString("NoRecordsFound", Culture)!;

    internal static string ParseErrorCount
        => ResourceManager.GetString("ParseErrorCount", Culture)!;

    internal static class Composite
    {
        internal static CompositeFormat HeadersGenerated => CompositeFormat.Parse(Messages.HeadersGenerated);
        internal static CompositeFormat HeaderFileSaved => CompositeFormat.Parse(Messages.HeaderFileSaved);
        internal static CompositeFormat RecordNameNotFound => CompositeFormat.Parse(Messages.RecordNameNotFound);
        internal static CompositeFormat ParseErrorCount => CompositeFormat.Parse(Messages.ParseErrorCount);
    }
}
