// <auto-generated/>
// This file is manually maintained to match Messages.resx.
// Update this file when Messages.resx changes.
#nullable enable

namespace CLICommonLibrary.Resources;

using System.Globalization;
using System.Resources;
using System.Text;

internal static class Messages
{
    private static ResourceManager? resourceMan;

    internal static ResourceManager ResourceManager
    {
        get
        {
            resourceMan ??= new ResourceManager("CLICommonLibrary.Resources.Messages", typeof(Messages).Assembly);
            return resourceMan;
        }
    }

    internal static CultureInfo? Culture { get; set; }

    internal static string ExceptionCount
        => ResourceManager.GetString("ExceptionCount", Culture)!;

    internal static string LogPathRequired
        => ResourceManager.GetString("LogPathRequired", Culture)!;

    internal static class Composite
    {
        internal static readonly CompositeFormat ExceptionCount = CompositeFormat.Parse(Messages.ExceptionCount);
    }
}
