// <auto-generated/>
// This file is manually maintained to match Messages.resx.
// Update this file when Messages.resx changes.
#nullable enable

namespace SchemaInfoScanner.Resources;

using System.Globalization;
using System.Resources;
using System.Text;

internal static class Messages
{
    private static ResourceManager? resourceMan;

    internal static ResourceManager ResourceManager
    {
        get
        {
            resourceMan ??= new ResourceManager("SchemaInfoScanner.Resources.Messages", typeof(Messages).Assembly);
            return resourceMan;
        }
    }

    internal static CultureInfo? Culture { get; set; }

    internal static string AlreadyVisited
        => ResourceManager.GetString("AlreadyVisited", Culture)!;

    internal static string Ignored
        => ResourceManager.GetString("Ignored", Culture)!;

    internal static string RecordStarted
        => ResourceManager.GetString("RecordStarted", Culture)!;

    internal static string RecordFinished
        => ResourceManager.GetString("RecordFinished", Culture)!;

    internal static string CodeNotCompilable
        => ResourceManager.GetString("CodeNotCompilable", Culture)!;

    internal static string NoStaticDataRecordFound
        => ResourceManager.GetString("NoStaticDataRecordFound", Culture)!;

    internal static string RecordSchemaNotFound
        => ResourceManager.GetString("RecordSchemaNotFound", Culture)!;

    internal static string ExceptionCountWhileCollecting
        => ResourceManager.GetString("ExceptionCountWhileCollecting", Culture)!;

    internal static string RecordNotNamedTypeSymbol
        => ResourceManager.GetString("RecordNotNamedTypeSymbol", Culture)!;

    internal static string ParseResultCountMismatch
        => ResourceManager.GetString("ParseResultCountMismatch", Culture)!;

    internal static string ParseResultParameterNotFound
        => ResourceManager.GetString("ParseResultParameterNotFound", Culture)!;

    internal static string AttributeHasNoProperty
        => ResourceManager.GetString("AttributeHasNoProperty", Culture)!;

    internal static string UnsupportedExpressionType
        => ResourceManager.GetString("UnsupportedExpressionType", Culture)!;

    internal static string ExpectedRecordCollectionType
        => ResourceManager.GetString("ExpectedRecordCollectionType", Culture)!;

    internal static string NotSupportedType
        => ResourceManager.GetString("NotSupportedType", Culture)!;

    internal static string RecordSchemaTypeArgNotFound
        => ResourceManager.GetString("RecordSchemaTypeArgNotFound", Culture)!;

    internal static string NullStringAttributeNotFound
        => ResourceManager.GetString("NullStringAttributeNotFound", Culture)!;

    internal static string RangeAttributeCannotBeUsedInEnum
        => ResourceManager.GetString("RangeAttributeCannotBeUsedInEnum", Culture)!;

    internal static string RangeAttributeMustHaveTwoValues
        => ResourceManager.GetString("RangeAttributeMustHaveTwoValues", Culture)!;

    internal static string ValueOutOfRange
        => ResourceManager.GetString("ValueOutOfRange", Culture)!;

    internal static string ParameterCannotHaveLengthAttribute
        => ResourceManager.GetString("ParameterCannotHaveLengthAttribute", Culture)!;

    internal static string ParameterCannotHaveLengthAttributeWithContext
        => ResourceManager.GetString("ParameterCannotHaveLengthAttributeWithContext", Culture)!;

    internal static string DuplicateKeyInContext
        => ResourceManager.GetString("DuplicateKeyInContext", Culture)!;

    internal static string InvalidDataLength
        => ResourceManager.GetString("InvalidDataLength", Culture)!;

    internal static string InvalidCellValue
        => ResourceManager.GetString("InvalidCellValue", Culture)!;

    internal static string InvalidCellValueWithPattern
        => ResourceManager.GetString("InvalidCellValueWithPattern", Culture)!;

    internal static string ValueTypeMustBeRecordPropertySchema
        => ResourceManager.GetString("ValueTypeMustBeRecordPropertySchema", Culture)!;

    internal static string ValueRecordMustHaveOneKeyMember
        => ResourceManager.GetString("ValueRecordMustHaveOneKeyMember", Culture)!;

    internal static string StartIndexOutOfRange
        => ResourceManager.GetString("StartIndexOutOfRange", Culture)!;

    internal static string UnreachableCodeInCollect
        => ResourceManager.GetString("UnreachableCodeInCollect", Culture)!;

    internal static string CannotValidateDuplicatesInNoneMode
        => ResourceManager.GetString("CannotValidateDuplicatesInNoneMode", Culture)!;

    internal static string DuplicateValuesInArgument
        => ResourceManager.GetString("DuplicateValuesInArgument", Culture)!;

    internal static string BeginKeyScopeOnlyInKeyOnlyMode
        => ResourceManager.GetString("BeginKeyScopeOnlyInKeyOnlyMode", Culture)!;

    internal static string NestedKeyScopesNotAllowed
        => ResourceManager.GetString("NestedKeyScopesNotAllowed", Culture)!;

    internal static string EndKeyScopeOnlyInKeyOnlyMode
        => ResourceManager.GetString("EndKeyScopeOnlyInKeyOnlyMode", Culture)!;

    internal static string EndKeyScopeWithoutBeginKeyScope
        => ResourceManager.GetString("EndKeyScopeWithoutBeginKeyScope", Culture)!;

    internal static string NoComponentsInKeyScope
        => ResourceManager.GetString("NoComponentsInKeyScope", Culture)!;

    internal static string ExpectedArrayType
        => ResourceManager.GetString("ExpectedArrayType", Culture)!;

    internal static string NullableRecordArrayNotSupported
        => ResourceManager.GetString("NullableRecordArrayNotSupported", Culture)!;

    internal static string SingleColumnArrayOnlyPrimitive
        => ResourceManager.GetString("SingleColumnArrayOnlyPrimitive", Culture)!;

    internal static string ExpectedHashSetType
        => ResourceManager.GetString("ExpectedHashSetType", Culture)!;

    internal static string NullableRecordHashSetNotSupported
        => ResourceManager.GetString("NullableRecordHashSetNotSupported", Culture)!;

    internal static string SingleColumnHashSetOnlyPrimitive
        => ResourceManager.GetString("SingleColumnHashSetOnlyPrimitive", Culture)!;

    internal static string ExpectedDictionaryType
        => ResourceManager.GetString("ExpectedDictionaryType", Culture)!;

    internal static string DictionaryKeyMustBeNonNullable
        => ResourceManager.GetString("DictionaryKeyMustBeNonNullable", Culture)!;

    internal static string DictionaryValueMustBeNonNullable
        => ResourceManager.GetString("DictionaryValueMustBeNonNullable", Culture)!;

    internal static string KeyAttributeRequiredInDictionaryValue
        => ResourceManager.GetString("KeyAttributeRequiredInDictionaryValue", Culture)!;

    internal static string DictionaryKeyValueMustBeSameType
        => ResourceManager.GetString("DictionaryKeyValueMustBeSameType", Culture)!;

    internal static string FileOrDirectoryNotExist
        => ResourceManager.GetString("FileOrDirectoryNotExist", Culture)!;

    internal static string NullableCollectionNotSupported
        => ResourceManager.GetString("NullableCollectionNotSupported", Culture)!;

    internal static string DateTimeFormatAttributeNotApplicable
        => ResourceManager.GetString("DateTimeFormatAttributeNotApplicable", Culture)!;

    internal static string DateTimeFormatAttributeRequired
        => ResourceManager.GetString("DateTimeFormatAttributeRequired", Culture)!;

    internal static string LengthAttributeRequired
        => ResourceManager.GetString("LengthAttributeRequired", Culture)!;

    internal static string NullStringAttributeRequiredForNullable
        => ResourceManager.GetString("NullStringAttributeRequiredForNullable", Culture)!;

    internal static string NullStringAttributeRequiredForNullableArray
        => ResourceManager.GetString("NullStringAttributeRequiredForNullableArray", Culture)!;

    internal static string NullStringAttributeRequiredForNullableSet
        => ResourceManager.GetString("NullStringAttributeRequiredForNullableSet", Culture)!;

    internal static string NullStringAttributeRequiredForNullableMap
        => ResourceManager.GetString("NullStringAttributeRequiredForNullableMap", Culture)!;

    internal static string NullStringAttributeNotAllowed
        => ResourceManager.GetString("NullStringAttributeNotAllowed", Culture)!;

    internal static string RegularExpressionAttributeOnlyForString
        => ResourceManager.GetString("RegularExpressionAttributeOnlyForString", Culture)!;

    internal static string SingleColumnCollectionNotForUnsupportedCollection
        => ResourceManager.GetString("SingleColumnCollectionNotForUnsupportedCollection", Culture)!;

    internal static string SingleColumnCollectionNotForMap
        => ResourceManager.GetString("SingleColumnCollectionNotForMap", Culture)!;

    internal static string TimeSpanFormatAttributeNotApplicable
        => ResourceManager.GetString("TimeSpanFormatAttributeNotApplicable", Culture)!;

    internal static string TimeSpanFormatAttributeRequired
        => ResourceManager.GetString("TimeSpanFormatAttributeRequired", Culture)!;

    internal static string InvalidCellValueForEnum
        => ResourceManager.GetString("InvalidCellValueForEnum", Culture)!;

    internal static string SingleColumnCellCountMismatch
        => ResourceManager.GetString("SingleColumnCellCountMismatch", Culture)!;

    internal static string SingleColumnCellEmptyValue
        => ResourceManager.GetString("SingleColumnCellEmptyValue", Culture)!;

    internal static string CompileErrorsOccurred
        => ResourceManager.GetString("CompileErrorsOccurred", Culture)!;

    internal static string NotSupportedRecordType
        => ResourceManager.GetString("NotSupportedRecordType", Culture)!;

    internal static string NotSupportedRecordTypeWithMessage
        => ResourceManager.GetString("NotSupportedRecordTypeWithMessage", Culture)!;

    internal static string NotFoundInRecordSchemaDictionary
        => ResourceManager.GetString("NotFoundInRecordSchemaDictionary", Culture)!;

    internal static string NotSupportedCollectionType
        => ResourceManager.GetString("NotSupportedCollectionType", Culture)!;

    internal static string NotSupportedPrimitiveType
        => ResourceManager.GetString("NotSupportedPrimitiveType", Culture)!;

    internal static string NotSupportedPropertyType
        => ResourceManager.GetString("NotSupportedPropertyType", Culture)!;

    internal static string FactoryNotSupportedPrimitiveType
        => ResourceManager.GetString("FactoryNotSupportedPrimitiveType", Culture)!;

    internal static string NotSupportedListType
        => ResourceManager.GetString("NotSupportedListType", Culture)!;

    internal static string NotSingleColumnList
        => ResourceManager.GetString("NotSingleColumnList", Culture)!;

    internal static string NotSupportedHashSetType
        => ResourceManager.GetString("NotSupportedHashSetType", Culture)!;

    internal static string NotSingleColumnHashSet
        => ResourceManager.GetString("NotSingleColumnHashSet", Culture)!;

    internal static string FactoryNotSupportedArrayType
        => ResourceManager.GetString("FactoryNotSupportedArrayType", Culture)!;

    internal static string IsRecordArrayType
        => ResourceManager.GetString("IsRecordArrayType", Culture)!;

    internal static string NotSupportedNestedCollectionType
        => ResourceManager.GetString("NotSupportedNestedCollectionType", Culture)!;

    internal static string FactoryDictionaryKeyMustBeRecordType
        => ResourceManager.GetString("FactoryDictionaryKeyMustBeRecordType", Culture)!;

    internal static string FactoryDictionaryValueMustBeRecordType
        => ResourceManager.GetString("FactoryDictionaryValueMustBeRecordType", Culture)!;

    internal static string FactoryDictionaryKeyMustBePrimitiveType
        => ResourceManager.GetString("FactoryDictionaryKeyMustBePrimitiveType", Culture)!;

    internal static string FactoryNotSupportedRecordType
        => ResourceManager.GetString("FactoryNotSupportedRecordType", Culture)!;

    internal static string IsRecordHashSetType
        => ResourceManager.GetString("IsRecordHashSetType", Culture)!;

    internal static string InvalidFullName
        => ResourceManager.GetString("InvalidFullName", Culture)!;

    internal static class Composite
    {
        internal static readonly CompositeFormat AlreadyVisited = CompositeFormat.Parse(Messages.AlreadyVisited);
        internal static readonly CompositeFormat Ignored = CompositeFormat.Parse(Messages.Ignored);
        internal static readonly CompositeFormat RecordStarted = CompositeFormat.Parse(Messages.RecordStarted);
        internal static readonly CompositeFormat RecordFinished = CompositeFormat.Parse(Messages.RecordFinished);
        internal static readonly CompositeFormat CodeNotCompilable = CompositeFormat.Parse(Messages.CodeNotCompilable);
        internal static readonly CompositeFormat RecordSchemaNotFound = CompositeFormat.Parse(Messages.RecordSchemaNotFound);
        internal static readonly CompositeFormat ExceptionCountWhileCollecting = CompositeFormat.Parse(Messages.ExceptionCountWhileCollecting);
        internal static readonly CompositeFormat RecordNotNamedTypeSymbol = CompositeFormat.Parse(Messages.RecordNotNamedTypeSymbol);
        internal static readonly CompositeFormat ParseResultParameterNotFound = CompositeFormat.Parse(Messages.ParseResultParameterNotFound);
        internal static readonly CompositeFormat AttributeHasNoProperty = CompositeFormat.Parse(Messages.AttributeHasNoProperty);
        internal static readonly CompositeFormat ExpectedRecordCollectionType = CompositeFormat.Parse(Messages.ExpectedRecordCollectionType);
        internal static readonly CompositeFormat NotSupportedType = CompositeFormat.Parse(Messages.NotSupportedType);
        internal static readonly CompositeFormat RecordSchemaTypeArgNotFound = CompositeFormat.Parse(Messages.RecordSchemaTypeArgNotFound);
        internal static readonly CompositeFormat NullStringAttributeNotFound = CompositeFormat.Parse(Messages.NullStringAttributeNotFound);
        internal static readonly CompositeFormat ValueOutOfRange = CompositeFormat.Parse(Messages.ValueOutOfRange);
        internal static readonly CompositeFormat ParameterCannotHaveLengthAttribute = CompositeFormat.Parse(Messages.ParameterCannotHaveLengthAttribute);
        internal static readonly CompositeFormat ParameterCannotHaveLengthAttributeWithContext = CompositeFormat.Parse(Messages.ParameterCannotHaveLengthAttributeWithContext);
        internal static readonly CompositeFormat DuplicateKeyInContext = CompositeFormat.Parse(Messages.DuplicateKeyInContext);
        internal static readonly CompositeFormat InvalidDataLength = CompositeFormat.Parse(Messages.InvalidDataLength);
        internal static readonly CompositeFormat InvalidCellValue = CompositeFormat.Parse(Messages.InvalidCellValue);
        internal static readonly CompositeFormat InvalidCellValueWithPattern = CompositeFormat.Parse(Messages.InvalidCellValueWithPattern);
        internal static readonly CompositeFormat ValueTypeMustBeRecordPropertySchema = CompositeFormat.Parse(Messages.ValueTypeMustBeRecordPropertySchema);
        internal static readonly CompositeFormat ValueRecordMustHaveOneKeyMember = CompositeFormat.Parse(Messages.ValueRecordMustHaveOneKeyMember);
        internal static readonly CompositeFormat StartIndexOutOfRange = CompositeFormat.Parse(Messages.StartIndexOutOfRange);
        internal static readonly CompositeFormat CannotValidateDuplicatesInNoneMode = CompositeFormat.Parse(Messages.CannotValidateDuplicatesInNoneMode);
        internal static readonly CompositeFormat DuplicateValuesInArgument = CompositeFormat.Parse(Messages.DuplicateValuesInArgument);
        internal static readonly CompositeFormat BeginKeyScopeOnlyInKeyOnlyMode = CompositeFormat.Parse(Messages.BeginKeyScopeOnlyInKeyOnlyMode);
        internal static readonly CompositeFormat NestedKeyScopesNotAllowed = CompositeFormat.Parse(Messages.NestedKeyScopesNotAllowed);
        internal static readonly CompositeFormat EndKeyScopeOnlyInKeyOnlyMode = CompositeFormat.Parse(Messages.EndKeyScopeOnlyInKeyOnlyMode);
        internal static readonly CompositeFormat EndKeyScopeWithoutBeginKeyScope = CompositeFormat.Parse(Messages.EndKeyScopeWithoutBeginKeyScope);
        internal static readonly CompositeFormat NoComponentsInKeyScope = CompositeFormat.Parse(Messages.NoComponentsInKeyScope);
        internal static readonly CompositeFormat ExpectedArrayType = CompositeFormat.Parse(Messages.ExpectedArrayType);
        internal static readonly CompositeFormat NullableRecordArrayNotSupported = CompositeFormat.Parse(Messages.NullableRecordArrayNotSupported);
        internal static readonly CompositeFormat SingleColumnArrayOnlyPrimitive = CompositeFormat.Parse(Messages.SingleColumnArrayOnlyPrimitive);
        internal static readonly CompositeFormat ExpectedHashSetType = CompositeFormat.Parse(Messages.ExpectedHashSetType);
        internal static readonly CompositeFormat NullableRecordHashSetNotSupported = CompositeFormat.Parse(Messages.NullableRecordHashSetNotSupported);
        internal static readonly CompositeFormat SingleColumnHashSetOnlyPrimitive = CompositeFormat.Parse(Messages.SingleColumnHashSetOnlyPrimitive);
        internal static readonly CompositeFormat ExpectedDictionaryType = CompositeFormat.Parse(Messages.ExpectedDictionaryType);
        internal static readonly CompositeFormat KeyAttributeRequiredInDictionaryValue = CompositeFormat.Parse(Messages.KeyAttributeRequiredInDictionaryValue);
        internal static readonly CompositeFormat NullableCollectionNotSupported = CompositeFormat.Parse(Messages.NullableCollectionNotSupported);
        internal static readonly CompositeFormat DateTimeFormatAttributeNotApplicable = CompositeFormat.Parse(Messages.DateTimeFormatAttributeNotApplicable);
        internal static readonly CompositeFormat DateTimeFormatAttributeRequired = CompositeFormat.Parse(Messages.DateTimeFormatAttributeRequired);
        internal static readonly CompositeFormat LengthAttributeRequired = CompositeFormat.Parse(Messages.LengthAttributeRequired);
        internal static readonly CompositeFormat NullStringAttributeRequiredForNullable = CompositeFormat.Parse(Messages.NullStringAttributeRequiredForNullable);
        internal static readonly CompositeFormat NullStringAttributeRequiredForNullableArray = CompositeFormat.Parse(Messages.NullStringAttributeRequiredForNullableArray);
        internal static readonly CompositeFormat NullStringAttributeRequiredForNullableSet = CompositeFormat.Parse(Messages.NullStringAttributeRequiredForNullableSet);
        internal static readonly CompositeFormat NullStringAttributeRequiredForNullableMap = CompositeFormat.Parse(Messages.NullStringAttributeRequiredForNullableMap);
        internal static readonly CompositeFormat NullStringAttributeNotAllowed = CompositeFormat.Parse(Messages.NullStringAttributeNotAllowed);
        internal static readonly CompositeFormat RegularExpressionAttributeOnlyForString = CompositeFormat.Parse(Messages.RegularExpressionAttributeOnlyForString);
        internal static readonly CompositeFormat SingleColumnCollectionNotForUnsupportedCollection = CompositeFormat.Parse(Messages.SingleColumnCollectionNotForUnsupportedCollection);
        internal static readonly CompositeFormat SingleColumnCollectionNotForMap = CompositeFormat.Parse(Messages.SingleColumnCollectionNotForMap);
        internal static readonly CompositeFormat TimeSpanFormatAttributeNotApplicable = CompositeFormat.Parse(Messages.TimeSpanFormatAttributeNotApplicable);
        internal static readonly CompositeFormat TimeSpanFormatAttributeRequired = CompositeFormat.Parse(Messages.TimeSpanFormatAttributeRequired);
        internal static readonly CompositeFormat InvalidCellValueForEnum = CompositeFormat.Parse(Messages.InvalidCellValueForEnum);
        internal static readonly CompositeFormat SingleColumnCellCountMismatch = CompositeFormat.Parse(Messages.SingleColumnCellCountMismatch);
        internal static readonly CompositeFormat SingleColumnCellEmptyValue = CompositeFormat.Parse(Messages.SingleColumnCellEmptyValue);
        internal static readonly CompositeFormat CompileErrorsOccurred = CompositeFormat.Parse(Messages.CompileErrorsOccurred);
        internal static readonly CompositeFormat NotSupportedRecordType = CompositeFormat.Parse(Messages.NotSupportedRecordType);
        internal static readonly CompositeFormat NotSupportedRecordTypeWithMessage = CompositeFormat.Parse(Messages.NotSupportedRecordTypeWithMessage);
        internal static readonly CompositeFormat NotFoundInRecordSchemaDictionary = CompositeFormat.Parse(Messages.NotFoundInRecordSchemaDictionary);
        internal static readonly CompositeFormat NotSupportedCollectionType = CompositeFormat.Parse(Messages.NotSupportedCollectionType);
        internal static readonly CompositeFormat NotSupportedPrimitiveType = CompositeFormat.Parse(Messages.NotSupportedPrimitiveType);
        internal static readonly CompositeFormat NotSupportedPropertyType = CompositeFormat.Parse(Messages.NotSupportedPropertyType);
        internal static readonly CompositeFormat FactoryNotSupportedPrimitiveType = CompositeFormat.Parse(Messages.FactoryNotSupportedPrimitiveType);
        internal static readonly CompositeFormat NotSupportedListType = CompositeFormat.Parse(Messages.NotSupportedListType);
        internal static readonly CompositeFormat NotSingleColumnList = CompositeFormat.Parse(Messages.NotSingleColumnList);
        internal static readonly CompositeFormat NotSupportedHashSetType = CompositeFormat.Parse(Messages.NotSupportedHashSetType);
        internal static readonly CompositeFormat NotSingleColumnHashSet = CompositeFormat.Parse(Messages.NotSingleColumnHashSet);
        internal static readonly CompositeFormat FactoryNotSupportedArrayType = CompositeFormat.Parse(Messages.FactoryNotSupportedArrayType);
        internal static readonly CompositeFormat IsRecordArrayType = CompositeFormat.Parse(Messages.IsRecordArrayType);
        internal static readonly CompositeFormat NotSupportedNestedCollectionType = CompositeFormat.Parse(Messages.NotSupportedNestedCollectionType);
        internal static readonly CompositeFormat FactoryDictionaryKeyMustBeRecordType = CompositeFormat.Parse(Messages.FactoryDictionaryKeyMustBeRecordType);
        internal static readonly CompositeFormat FactoryDictionaryValueMustBeRecordType = CompositeFormat.Parse(Messages.FactoryDictionaryValueMustBeRecordType);
        internal static readonly CompositeFormat FactoryDictionaryKeyMustBePrimitiveType = CompositeFormat.Parse(Messages.FactoryDictionaryKeyMustBePrimitiveType);
        internal static readonly CompositeFormat FactoryNotSupportedRecordType = CompositeFormat.Parse(Messages.FactoryNotSupportedRecordType);
        internal static readonly CompositeFormat IsRecordHashSetType = CompositeFormat.Parse(Messages.IsRecordHashSetType);
    }
}
