// <auto-generated/>
// This file is manually maintained to match Messages.resx.
// Update this file when Messages.resx changes.
#nullable enable

namespace SchemaInfoScanner.Resources;

using System.Globalization;
using System.Resources;
using System.Text;

internal static class Messages
{
    private static ResourceManager? resourceMan;

    internal static ResourceManager ResourceManager
    {
        get
        {
            resourceMan ??= new ResourceManager("SchemaInfoScanner.Resources.Messages", typeof(Messages).Assembly);
            return resourceMan;
        }
    }

    internal static CultureInfo? Culture { get; set; }

    internal static string AlreadyVisited
        => ResourceManager.GetString("AlreadyVisited", Culture)!;

    internal static string Ignored
        => ResourceManager.GetString("Ignored", Culture)!;

    internal static string RecordStarted
        => ResourceManager.GetString("RecordStarted", Culture)!;

    internal static string RecordFinished
        => ResourceManager.GetString("RecordFinished", Culture)!;

    internal static string CodeNotCompilable
        => ResourceManager.GetString("CodeNotCompilable", Culture)!;

    internal static string NoStaticDataRecordFound
        => ResourceManager.GetString("NoStaticDataRecordFound", Culture)!;

    internal static string RecordSchemaNotFound
        => ResourceManager.GetString("RecordSchemaNotFound", Culture)!;

    internal static string ExceptionCountWhileCollecting
        => ResourceManager.GetString("ExceptionCountWhileCollecting", Culture)!;

    internal static string RecordNotNamedTypeSymbol
        => ResourceManager.GetString("RecordNotNamedTypeSymbol", Culture)!;

    internal static string ParseResultCountMismatch
        => ResourceManager.GetString("ParseResultCountMismatch", Culture)!;

    internal static string ParseResultParameterNotFound
        => ResourceManager.GetString("ParseResultParameterNotFound", Culture)!;

    internal static string AttributeHasNoProperty
        => ResourceManager.GetString("AttributeHasNoProperty", Culture)!;

    internal static string UnsupportedExpressionType
        => ResourceManager.GetString("UnsupportedExpressionType", Culture)!;

    internal static string ExpectedRecordCollectionType
        => ResourceManager.GetString("ExpectedRecordCollectionType", Culture)!;

    internal static string NotSupportedType
        => ResourceManager.GetString("NotSupportedType", Culture)!;

    internal static string RecordSchemaTypeArgNotFound
        => ResourceManager.GetString("RecordSchemaTypeArgNotFound", Culture)!;

    internal static string NullStringAttributeNotFound
        => ResourceManager.GetString("NullStringAttributeNotFound", Culture)!;

    internal static string RangeAttributeCannotBeUsedInEnum
        => ResourceManager.GetString("RangeAttributeCannotBeUsedInEnum", Culture)!;

    internal static string RangeAttributeMustHaveTwoValues
        => ResourceManager.GetString("RangeAttributeMustHaveTwoValues", Culture)!;

    internal static string ValueOutOfRange
        => ResourceManager.GetString("ValueOutOfRange", Culture)!;

    internal static string ParameterCannotHaveLengthAttribute
        => ResourceManager.GetString("ParameterCannotHaveLengthAttribute", Culture)!;

    internal static string ParameterCannotHaveLengthAttributeWithContext
        => ResourceManager.GetString("ParameterCannotHaveLengthAttributeWithContext", Culture)!;

    internal static string DuplicateKeyInContext
        => ResourceManager.GetString("DuplicateKeyInContext", Culture)!;

    internal static string InvalidDataLength
        => ResourceManager.GetString("InvalidDataLength", Culture)!;

    internal static string InvalidCellValue
        => ResourceManager.GetString("InvalidCellValue", Culture)!;

    internal static string InvalidCellValueWithPattern
        => ResourceManager.GetString("InvalidCellValueWithPattern", Culture)!;

    internal static string ValueTypeMustBeRecordPropertySchema
        => ResourceManager.GetString("ValueTypeMustBeRecordPropertySchema", Culture)!;

    internal static string ValueRecordMustHaveOneKeyMember
        => ResourceManager.GetString("ValueRecordMustHaveOneKeyMember", Culture)!;

    internal static string StartIndexOutOfRange
        => ResourceManager.GetString("StartIndexOutOfRange", Culture)!;

    internal static string UnreachableCodeInCollect
        => ResourceManager.GetString("UnreachableCodeInCollect", Culture)!;

    internal static string CannotValidateDuplicatesInNoneMode
        => ResourceManager.GetString("CannotValidateDuplicatesInNoneMode", Culture)!;

    internal static string DuplicateValuesInArgument
        => ResourceManager.GetString("DuplicateValuesInArgument", Culture)!;

    internal static string BeginKeyScopeOnlyInKeyOnlyMode
        => ResourceManager.GetString("BeginKeyScopeOnlyInKeyOnlyMode", Culture)!;

    internal static string NestedKeyScopesNotAllowed
        => ResourceManager.GetString("NestedKeyScopesNotAllowed", Culture)!;

    internal static string EndKeyScopeOnlyInKeyOnlyMode
        => ResourceManager.GetString("EndKeyScopeOnlyInKeyOnlyMode", Culture)!;

    internal static string EndKeyScopeWithoutBeginKeyScope
        => ResourceManager.GetString("EndKeyScopeWithoutBeginKeyScope", Culture)!;

    internal static string NoComponentsInKeyScope
        => ResourceManager.GetString("NoComponentsInKeyScope", Culture)!;

    internal static string ExpectedArrayType
        => ResourceManager.GetString("ExpectedArrayType", Culture)!;

    internal static string NullableRecordArrayNotSupported
        => ResourceManager.GetString("NullableRecordArrayNotSupported", Culture)!;

    internal static string SingleColumnArrayOnlyPrimitive
        => ResourceManager.GetString("SingleColumnArrayOnlyPrimitive", Culture)!;

    internal static string ExpectedHashSetType
        => ResourceManager.GetString("ExpectedHashSetType", Culture)!;

    internal static string NullableRecordHashSetNotSupported
        => ResourceManager.GetString("NullableRecordHashSetNotSupported", Culture)!;

    internal static string SingleColumnHashSetOnlyPrimitive
        => ResourceManager.GetString("SingleColumnHashSetOnlyPrimitive", Culture)!;

    internal static string ExpectedDictionaryType
        => ResourceManager.GetString("ExpectedDictionaryType", Culture)!;

    internal static string DictionaryKeyMustBeNonNullable
        => ResourceManager.GetString("DictionaryKeyMustBeNonNullable", Culture)!;

    internal static string DictionaryValueMustBeNonNullable
        => ResourceManager.GetString("DictionaryValueMustBeNonNullable", Culture)!;

    internal static string KeyAttributeRequiredInDictionaryValue
        => ResourceManager.GetString("KeyAttributeRequiredInDictionaryValue", Culture)!;

    internal static string DictionaryKeyValueMustBeSameType
        => ResourceManager.GetString("DictionaryKeyValueMustBeSameType", Culture)!;

    internal static string FileOrDirectoryNotExist
        => ResourceManager.GetString("FileOrDirectoryNotExist", Culture)!;

    internal static string NullableCollectionNotSupported
        => ResourceManager.GetString("NullableCollectionNotSupported", Culture)!;

    internal static string KeyAttributeMustBeNonNullable
        => ResourceManager.GetString("KeyAttributeMustBeNonNullable", Culture)!;

    internal static string StaticDataRecordMustHaveAtMostOneKey
        => ResourceManager.GetString("StaticDataRecordMustHaveAtMostOneKey", Culture)!;

    internal static string DateTimeFormatAttributeNotApplicable
        => ResourceManager.GetString("DateTimeFormatAttributeNotApplicable", Culture)!;

    internal static string DateTimeFormatAttributeRequired
        => ResourceManager.GetString("DateTimeFormatAttributeRequired", Culture)!;

    internal static string LengthAttributeRequired
        => ResourceManager.GetString("LengthAttributeRequired", Culture)!;

    internal static string NullStringAttributeRequiredForNullable
        => ResourceManager.GetString("NullStringAttributeRequiredForNullable", Culture)!;

    internal static string NullStringAttributeRequiredForNullableArray
        => ResourceManager.GetString("NullStringAttributeRequiredForNullableArray", Culture)!;

    internal static string NullStringAttributeRequiredForNullableSet
        => ResourceManager.GetString("NullStringAttributeRequiredForNullableSet", Culture)!;

    internal static string NullStringAttributeRequiredForNullableMap
        => ResourceManager.GetString("NullStringAttributeRequiredForNullableMap", Culture)!;

    internal static string NullStringAttributeNotAllowed
        => ResourceManager.GetString("NullStringAttributeNotAllowed", Culture)!;

    internal static string RegularExpressionAttributeOnlyForString
        => ResourceManager.GetString("RegularExpressionAttributeOnlyForString", Culture)!;

    internal static string CountRangeAttributeOnlyForSingleColumnCollection
        => ResourceManager.GetString("CountRangeAttributeOnlyForSingleColumnCollection", Culture)!;

    internal static string CountRangeAndLengthMutuallyExclusive
        => ResourceManager.GetString("CountRangeAndLengthMutuallyExclusive", Culture)!;

    internal static string CountRangeMinMustBePositive
        => ResourceManager.GetString("CountRangeMinMustBePositive", Culture)!;

    internal static string CountOutOfRange
        => ResourceManager.GetString("CountOutOfRange", Culture)!;

    internal static string SingleColumnCollectionNotForUnsupportedCollection
        => ResourceManager.GetString("SingleColumnCollectionNotForUnsupportedCollection", Culture)!;

    internal static string SingleColumnCollectionNotForMap
        => ResourceManager.GetString("SingleColumnCollectionNotForMap", Culture)!;

    internal static string FkSwitchFkConflict
        => ResourceManager.GetString("FkSwitchFkConflict", Culture)!;

    internal static string SwitchForeignKeyDuplicateCondition
        => ResourceManager.GetString("SwitchForeignKeyDuplicateCondition", Culture)!;

    internal static string TimeSpanFormatAttributeNotApplicable
        => ResourceManager.GetString("TimeSpanFormatAttributeNotApplicable", Culture)!;

    internal static string TimeSpanFormatAttributeRequired
        => ResourceManager.GetString("TimeSpanFormatAttributeRequired", Culture)!;

    internal static string InvalidCellValueForEnum
        => ResourceManager.GetString("InvalidCellValueForEnum", Culture)!;

    internal static string SingleColumnCellCountMismatch
        => ResourceManager.GetString("SingleColumnCellCountMismatch", Culture)!;

    internal static string SingleColumnCellEmptyValue
        => ResourceManager.GetString("SingleColumnCellEmptyValue", Culture)!;

    internal static string CompileErrorsOccurred
        => ResourceManager.GetString("CompileErrorsOccurred", Culture)!;

    internal static string NotSupportedRecordType
        => ResourceManager.GetString("NotSupportedRecordType", Culture)!;

    internal static string NotSupportedRecordTypeWithMessage
        => ResourceManager.GetString("NotSupportedRecordTypeWithMessage", Culture)!;

    internal static string NotFoundInRecordSchemaDictionary
        => ResourceManager.GetString("NotFoundInRecordSchemaDictionary", Culture)!;

    internal static string NotSupportedCollectionType
        => ResourceManager.GetString("NotSupportedCollectionType", Culture)!;

    internal static string NotSupportedPrimitiveType
        => ResourceManager.GetString("NotSupportedPrimitiveType", Culture)!;

    internal static string NotSupportedPropertyType
        => ResourceManager.GetString("NotSupportedPropertyType", Culture)!;

    internal static string FactoryNotSupportedPrimitiveType
        => ResourceManager.GetString("FactoryNotSupportedPrimitiveType", Culture)!;

    internal static string NotSupportedListType
        => ResourceManager.GetString("NotSupportedListType", Culture)!;

    internal static string NotSingleColumnList
        => ResourceManager.GetString("NotSingleColumnList", Culture)!;

    internal static string NotSupportedHashSetType
        => ResourceManager.GetString("NotSupportedHashSetType", Culture)!;

    internal static string NotSingleColumnHashSet
        => ResourceManager.GetString("NotSingleColumnHashSet", Culture)!;

    internal static string FactoryNotSupportedArrayType
        => ResourceManager.GetString("FactoryNotSupportedArrayType", Culture)!;

    internal static string IsRecordArrayType
        => ResourceManager.GetString("IsRecordArrayType", Culture)!;

    internal static string NotSupportedNestedCollectionType
        => ResourceManager.GetString("NotSupportedNestedCollectionType", Culture)!;

    internal static string FactoryDictionaryKeyMustBeRecordType
        => ResourceManager.GetString("FactoryDictionaryKeyMustBeRecordType", Culture)!;

    internal static string FactoryDictionaryValueMustBeRecordType
        => ResourceManager.GetString("FactoryDictionaryValueMustBeRecordType", Culture)!;

    internal static string FactoryDictionaryKeyMustBePrimitiveType
        => ResourceManager.GetString("FactoryDictionaryKeyMustBePrimitiveType", Culture)!;

    internal static string FactoryNotSupportedRecordType
        => ResourceManager.GetString("FactoryNotSupportedRecordType", Culture)!;

    internal static string IsRecordHashSetType
        => ResourceManager.GetString("IsRecordHashSetType", Culture)!;

    internal static string InvalidFullName
        => ResourceManager.GetString("InvalidFullName", Culture)!;

    internal static class Composite
    {
        internal static CompositeFormat AlreadyVisited => CompositeFormat.Parse(Messages.AlreadyVisited);
        internal static CompositeFormat Ignored => CompositeFormat.Parse(Messages.Ignored);
        internal static CompositeFormat RecordStarted => CompositeFormat.Parse(Messages.RecordStarted);
        internal static CompositeFormat RecordFinished => CompositeFormat.Parse(Messages.RecordFinished);
        internal static CompositeFormat CodeNotCompilable => CompositeFormat.Parse(Messages.CodeNotCompilable);
        internal static CompositeFormat RecordSchemaNotFound => CompositeFormat.Parse(Messages.RecordSchemaNotFound);
        internal static CompositeFormat ExceptionCountWhileCollecting => CompositeFormat.Parse(Messages.ExceptionCountWhileCollecting);
        internal static CompositeFormat RecordNotNamedTypeSymbol => CompositeFormat.Parse(Messages.RecordNotNamedTypeSymbol);
        internal static CompositeFormat ParseResultParameterNotFound => CompositeFormat.Parse(Messages.ParseResultParameterNotFound);
        internal static CompositeFormat AttributeHasNoProperty => CompositeFormat.Parse(Messages.AttributeHasNoProperty);
        internal static CompositeFormat ExpectedRecordCollectionType => CompositeFormat.Parse(Messages.ExpectedRecordCollectionType);
        internal static CompositeFormat NotSupportedType => CompositeFormat.Parse(Messages.NotSupportedType);
        internal static CompositeFormat RecordSchemaTypeArgNotFound => CompositeFormat.Parse(Messages.RecordSchemaTypeArgNotFound);
        internal static CompositeFormat NullStringAttributeNotFound => CompositeFormat.Parse(Messages.NullStringAttributeNotFound);
        internal static CompositeFormat ValueOutOfRange => CompositeFormat.Parse(Messages.ValueOutOfRange);
        internal static CompositeFormat ParameterCannotHaveLengthAttribute => CompositeFormat.Parse(Messages.ParameterCannotHaveLengthAttribute);
        internal static CompositeFormat ParameterCannotHaveLengthAttributeWithContext => CompositeFormat.Parse(Messages.ParameterCannotHaveLengthAttributeWithContext);
        internal static CompositeFormat DuplicateKeyInContext => CompositeFormat.Parse(Messages.DuplicateKeyInContext);
        internal static CompositeFormat InvalidDataLength => CompositeFormat.Parse(Messages.InvalidDataLength);
        internal static CompositeFormat InvalidCellValue => CompositeFormat.Parse(Messages.InvalidCellValue);
        internal static CompositeFormat InvalidCellValueWithPattern => CompositeFormat.Parse(Messages.InvalidCellValueWithPattern);
        internal static CompositeFormat ValueTypeMustBeRecordPropertySchema => CompositeFormat.Parse(Messages.ValueTypeMustBeRecordPropertySchema);
        internal static CompositeFormat ValueRecordMustHaveOneKeyMember => CompositeFormat.Parse(Messages.ValueRecordMustHaveOneKeyMember);
        internal static CompositeFormat StartIndexOutOfRange => CompositeFormat.Parse(Messages.StartIndexOutOfRange);
        internal static CompositeFormat CannotValidateDuplicatesInNoneMode => CompositeFormat.Parse(Messages.CannotValidateDuplicatesInNoneMode);
        internal static CompositeFormat DuplicateValuesInArgument => CompositeFormat.Parse(Messages.DuplicateValuesInArgument);
        internal static CompositeFormat BeginKeyScopeOnlyInKeyOnlyMode => CompositeFormat.Parse(Messages.BeginKeyScopeOnlyInKeyOnlyMode);
        internal static CompositeFormat NestedKeyScopesNotAllowed => CompositeFormat.Parse(Messages.NestedKeyScopesNotAllowed);
        internal static CompositeFormat EndKeyScopeOnlyInKeyOnlyMode => CompositeFormat.Parse(Messages.EndKeyScopeOnlyInKeyOnlyMode);
        internal static CompositeFormat EndKeyScopeWithoutBeginKeyScope => CompositeFormat.Parse(Messages.EndKeyScopeWithoutBeginKeyScope);
        internal static CompositeFormat NoComponentsInKeyScope => CompositeFormat.Parse(Messages.NoComponentsInKeyScope);
        internal static CompositeFormat ExpectedArrayType => CompositeFormat.Parse(Messages.ExpectedArrayType);
        internal static CompositeFormat NullableRecordArrayNotSupported => CompositeFormat.Parse(Messages.NullableRecordArrayNotSupported);
        internal static CompositeFormat SingleColumnArrayOnlyPrimitive => CompositeFormat.Parse(Messages.SingleColumnArrayOnlyPrimitive);
        internal static CompositeFormat ExpectedHashSetType => CompositeFormat.Parse(Messages.ExpectedHashSetType);
        internal static CompositeFormat NullableRecordHashSetNotSupported => CompositeFormat.Parse(Messages.NullableRecordHashSetNotSupported);
        internal static CompositeFormat SingleColumnHashSetOnlyPrimitive => CompositeFormat.Parse(Messages.SingleColumnHashSetOnlyPrimitive);
        internal static CompositeFormat ExpectedDictionaryType => CompositeFormat.Parse(Messages.ExpectedDictionaryType);
        internal static CompositeFormat KeyAttributeRequiredInDictionaryValue => CompositeFormat.Parse(Messages.KeyAttributeRequiredInDictionaryValue);
        internal static CompositeFormat NullableCollectionNotSupported => CompositeFormat.Parse(Messages.NullableCollectionNotSupported);
        internal static CompositeFormat KeyAttributeMustBeNonNullable => CompositeFormat.Parse(Messages.KeyAttributeMustBeNonNullable);
        internal static CompositeFormat StaticDataRecordMustHaveAtMostOneKey => CompositeFormat.Parse(Messages.StaticDataRecordMustHaveAtMostOneKey);
        internal static CompositeFormat DateTimeFormatAttributeNotApplicable => CompositeFormat.Parse(Messages.DateTimeFormatAttributeNotApplicable);
        internal static CompositeFormat DateTimeFormatAttributeRequired => CompositeFormat.Parse(Messages.DateTimeFormatAttributeRequired);
        internal static CompositeFormat LengthAttributeRequired => CompositeFormat.Parse(Messages.LengthAttributeRequired);
        internal static CompositeFormat NullStringAttributeRequiredForNullable => CompositeFormat.Parse(Messages.NullStringAttributeRequiredForNullable);
        internal static CompositeFormat NullStringAttributeRequiredForNullableArray => CompositeFormat.Parse(Messages.NullStringAttributeRequiredForNullableArray);
        internal static CompositeFormat NullStringAttributeRequiredForNullableSet => CompositeFormat.Parse(Messages.NullStringAttributeRequiredForNullableSet);
        internal static CompositeFormat NullStringAttributeRequiredForNullableMap => CompositeFormat.Parse(Messages.NullStringAttributeRequiredForNullableMap);
        internal static CompositeFormat NullStringAttributeNotAllowed => CompositeFormat.Parse(Messages.NullStringAttributeNotAllowed);
        internal static CompositeFormat RegularExpressionAttributeOnlyForString => CompositeFormat.Parse(Messages.RegularExpressionAttributeOnlyForString);
        internal static CompositeFormat CountRangeAttributeOnlyForSingleColumnCollection => CompositeFormat.Parse(Messages.CountRangeAttributeOnlyForSingleColumnCollection);
        internal static CompositeFormat CountOutOfRange => CompositeFormat.Parse(Messages.CountOutOfRange);
        internal static CompositeFormat SingleColumnCollectionNotForUnsupportedCollection => CompositeFormat.Parse(Messages.SingleColumnCollectionNotForUnsupportedCollection);
        internal static CompositeFormat SingleColumnCollectionNotForMap => CompositeFormat.Parse(Messages.SingleColumnCollectionNotForMap);
        internal static CompositeFormat FkSwitchFkConflict => CompositeFormat.Parse(Messages.FkSwitchFkConflict);
        internal static CompositeFormat SwitchForeignKeyDuplicateCondition => CompositeFormat.Parse(Messages.SwitchForeignKeyDuplicateCondition);
        internal static CompositeFormat TimeSpanFormatAttributeNotApplicable => CompositeFormat.Parse(Messages.TimeSpanFormatAttributeNotApplicable);
        internal static CompositeFormat TimeSpanFormatAttributeRequired => CompositeFormat.Parse(Messages.TimeSpanFormatAttributeRequired);
        internal static CompositeFormat InvalidCellValueForEnum => CompositeFormat.Parse(Messages.InvalidCellValueForEnum);
        internal static CompositeFormat SingleColumnCellCountMismatch => CompositeFormat.Parse(Messages.SingleColumnCellCountMismatch);
        internal static CompositeFormat SingleColumnCellEmptyValue => CompositeFormat.Parse(Messages.SingleColumnCellEmptyValue);
        internal static CompositeFormat CompileErrorsOccurred => CompositeFormat.Parse(Messages.CompileErrorsOccurred);
        internal static CompositeFormat NotSupportedRecordType => CompositeFormat.Parse(Messages.NotSupportedRecordType);
        internal static CompositeFormat NotSupportedRecordTypeWithMessage => CompositeFormat.Parse(Messages.NotSupportedRecordTypeWithMessage);
        internal static CompositeFormat NotFoundInRecordSchemaDictionary => CompositeFormat.Parse(Messages.NotFoundInRecordSchemaDictionary);
        internal static CompositeFormat NotSupportedCollectionType => CompositeFormat.Parse(Messages.NotSupportedCollectionType);
        internal static CompositeFormat NotSupportedPrimitiveType => CompositeFormat.Parse(Messages.NotSupportedPrimitiveType);
        internal static CompositeFormat NotSupportedPropertyType => CompositeFormat.Parse(Messages.NotSupportedPropertyType);
        internal static CompositeFormat FactoryNotSupportedPrimitiveType => CompositeFormat.Parse(Messages.FactoryNotSupportedPrimitiveType);
        internal static CompositeFormat NotSupportedListType => CompositeFormat.Parse(Messages.NotSupportedListType);
        internal static CompositeFormat NotSingleColumnList => CompositeFormat.Parse(Messages.NotSingleColumnList);
        internal static CompositeFormat NotSupportedHashSetType => CompositeFormat.Parse(Messages.NotSupportedHashSetType);
        internal static CompositeFormat NotSingleColumnHashSet => CompositeFormat.Parse(Messages.NotSingleColumnHashSet);
        internal static CompositeFormat FactoryNotSupportedArrayType => CompositeFormat.Parse(Messages.FactoryNotSupportedArrayType);
        internal static CompositeFormat IsRecordArrayType => CompositeFormat.Parse(Messages.IsRecordArrayType);
        internal static CompositeFormat NotSupportedNestedCollectionType => CompositeFormat.Parse(Messages.NotSupportedNestedCollectionType);
        internal static CompositeFormat FactoryDictionaryKeyMustBeRecordType => CompositeFormat.Parse(Messages.FactoryDictionaryKeyMustBeRecordType);
        internal static CompositeFormat FactoryDictionaryValueMustBeRecordType => CompositeFormat.Parse(Messages.FactoryDictionaryValueMustBeRecordType);
        internal static CompositeFormat FactoryDictionaryKeyMustBePrimitiveType => CompositeFormat.Parse(Messages.FactoryDictionaryKeyMustBePrimitiveType);
        internal static CompositeFormat FactoryNotSupportedRecordType => CompositeFormat.Parse(Messages.FactoryNotSupportedRecordType);
        internal static CompositeFormat IsRecordHashSetType => CompositeFormat.Parse(Messages.IsRecordHashSetType);
    }
}
