// <auto-generated/>
// This file is manually maintained to match Messages.resx.
// Update this file when Messages.resx changes.
#nullable enable

namespace Sdp.Resources;

using System.Globalization;
using System.Resources;
using System.Text;

internal static class Messages
{
    private static ResourceManager? resourceMan;

    internal static ResourceManager ResourceManager
    {
        get
        {
            resourceMan ??= new ResourceManager("Sdp.Resources.Messages", typeof(Messages).Assembly);
            return resourceMan;
        }
    }

    internal static CultureInfo? Culture { get; set; }

    internal static string TablesFailedToLoad
        => ResourceManager.GetString("TablesFailedToLoad", Culture)!;

    internal static string InvalidTableParameter
        => ResourceManager.GetString("InvalidTableParameter", Culture)!;

    internal static string FkTargetNotFound
        => ResourceManager.GetString("FkTargetNotFound", Culture)!;

    internal static string IndexNotRegistered
        => ResourceManager.GetString("IndexNotRegistered", Culture)!;

    internal static string FkValueNotFound
        => ResourceManager.GetString("FkValueNotFound", Culture)!;

    internal static string FkValidationFailed
        => ResourceManager.GetString("FkValidationFailed", Culture)!;

    internal static string KeySelectorInvalid
        => ResourceManager.GetString("KeySelectorInvalid", Culture)!;

    internal static string StaticDataRecordAttributeRequired
        => ResourceManager.GetString("StaticDataRecordAttributeRequired", Culture)!;

    internal static string DuplicateKey
        => ResourceManager.GetString("DuplicateKey", Culture)!;

    internal static string KeyNotFound
        => ResourceManager.GetString("KeyNotFound", Culture)!;

    internal static string CsvRowWithFile
        => ResourceManager.GetString("CsvRowWithFile", Culture)!;

    internal static string CsvRowWithoutFile
        => ResourceManager.GetString("CsvRowWithoutFile", Culture)!;

    internal static string CsvRowParseError
        => ResourceManager.GetString("CsvRowParseError", Culture)!;

    internal static string CsvHeaderNotFound
        => ResourceManager.GetString("CsvHeaderNotFound", Culture)!;

    internal static string EnumValueNotDefined
        => ResourceManager.GetString("EnumValueNotDefined", Culture)!;

    internal static string UnknownCollectionType
        => ResourceManager.GetString("UnknownCollectionType", Culture)!;

    internal static string KeyAttributeRequired
        => ResourceManager.GetString("KeyAttributeRequired", Culture)!;

    internal static string KeyPropertyNotFound
        => ResourceManager.GetString("KeyPropertyNotFound", Culture)!;

    internal static class Composite
    {
        internal static readonly CompositeFormat InvalidTableParameter = CompositeFormat.Parse(Messages.InvalidTableParameter);
        internal static readonly CompositeFormat FkTargetNotFound = CompositeFormat.Parse(Messages.FkTargetNotFound);
        internal static readonly CompositeFormat IndexNotRegistered = CompositeFormat.Parse(Messages.IndexNotRegistered);
        internal static readonly CompositeFormat FkValueNotFound = CompositeFormat.Parse(Messages.FkValueNotFound);
        internal static readonly CompositeFormat StaticDataRecordAttributeRequired = CompositeFormat.Parse(Messages.StaticDataRecordAttributeRequired);
        internal static readonly CompositeFormat DuplicateKey = CompositeFormat.Parse(Messages.DuplicateKey);
        internal static readonly CompositeFormat KeyNotFound = CompositeFormat.Parse(Messages.KeyNotFound);
        internal static readonly CompositeFormat CsvRowWithFile = CompositeFormat.Parse(Messages.CsvRowWithFile);
        internal static readonly CompositeFormat CsvRowWithoutFile = CompositeFormat.Parse(Messages.CsvRowWithoutFile);
        internal static readonly CompositeFormat CsvRowParseError = CompositeFormat.Parse(Messages.CsvRowParseError);
        internal static readonly CompositeFormat CsvHeaderNotFound = CompositeFormat.Parse(Messages.CsvHeaderNotFound);
        internal static readonly CompositeFormat EnumValueNotDefined = CompositeFormat.Parse(Messages.EnumValueNotDefined);
        internal static readonly CompositeFormat UnknownCollectionType = CompositeFormat.Parse(Messages.UnknownCollectionType);
        internal static readonly CompositeFormat KeyAttributeRequired = CompositeFormat.Parse(Messages.KeyAttributeRequired);
        internal static readonly CompositeFormat KeyPropertyNotFound = CompositeFormat.Parse(Messages.KeyPropertyNotFound);
    }
}
