// <auto-generated/>
// This file is manually maintained to match Messages.resx.
// Update this file when Messages.resx changes.
#nullable enable

namespace ExcelColumnExtractor.Resources;

using System.Globalization;
using System.Resources;
using System.Text;

internal static class Messages
{
    private static ResourceManager? resourceMan;

    internal static ResourceManager ResourceManager
    {
        get
        {
            resourceMan ??= new ResourceManager("ExcelColumnExtractor.Resources.Messages", typeof(Messages).Assembly);
            return resourceMan;
        }
    }

    internal static CultureInfo? Culture { get; set; }

    internal static string FileAlreadyOpen
        => ResourceManager.GetString("FileAlreadyOpen", Culture)!;

    internal static string FileAdded
        => ResourceManager.GetString("FileAdded", Culture)!;

    internal static string FileRemoved
        => ResourceManager.GetString("FileRemoved", Culture)!;

    internal static string FileUpdated
        => ResourceManager.GetString("FileUpdated", Culture)!;

    internal static string SheetScanned
        => ResourceManager.GetString("SheetScanned", Culture)!;

    internal static string FolderPathsDifferent
        => ResourceManager.GetString("FolderPathsDifferent", Culture)!;

    internal static string FileUpdatedBeforeCapture
        => ResourceManager.GetString("FileUpdatedBeforeCapture", Culture)!;

    internal static string HeaderAndIndexCountMismatch
        => ResourceManager.GetString("HeaderAndIndexCountMismatch", Culture)!;

    internal static string HeadersLine
        => ResourceManager.GetString("HeadersLine", Culture)!;

    internal static string IndexSetLine
        => ResourceManager.GetString("IndexSetLine", Culture)!;

    internal static string RequiredHeaderNotFound
        => ResourceManager.GetString("RequiredHeaderNotFound", Culture)!;

    internal static string SheetHeadersLine
        => ResourceManager.GetString("SheetHeadersLine", Culture)!;

    internal static string RecordHeadersLine
        => ResourceManager.GetString("RecordHeadersLine", Culture)!;

    internal static string HeaderCaseSensitivity
        => ResourceManager.GetString("HeaderCaseSensitivity", Culture)!;

    internal static string SheetNotFound
        => ResourceManager.GetString("SheetNotFound", Culture)!;

    internal static string UnexpectedEndOfSheet
        => ResourceManager.GetString("UnexpectedEndOfSheet", Culture)!;

    internal static string CellAddressRequired
        => ResourceManager.GetString("CellAddressRequired", Culture)!;

    internal static string UnexpectedEndOfSheetWithStartCell
        => ResourceManager.GetString("UnexpectedEndOfSheetWithStartCell", Culture)!;

    internal static string FileOrDirectoryNotExist
        => ResourceManager.GetString("FileOrDirectoryNotExist", Culture)!;

    internal static string StaticDataRecordAttributeNotFound
        => ResourceManager.GetString("StaticDataRecordAttributeNotFound", Culture)!;

    internal static string DirectoryAlreadyHasFiles
        => ResourceManager.GetString("DirectoryAlreadyHasFiles", Culture)!;

    internal static string ParseErrorCount
        => ResourceManager.GetString("ParseErrorCount", Culture)!;

    internal static class Composite
    {
        internal static readonly CompositeFormat FileAlreadyOpen = CompositeFormat.Parse(Messages.FileAlreadyOpen);
        internal static readonly CompositeFormat FileAdded = CompositeFormat.Parse(Messages.FileAdded);
        internal static readonly CompositeFormat FileRemoved = CompositeFormat.Parse(Messages.FileRemoved);
        internal static readonly CompositeFormat FileUpdated = CompositeFormat.Parse(Messages.FileUpdated);
        internal static readonly CompositeFormat SheetScanned = CompositeFormat.Parse(Messages.SheetScanned);
        internal static readonly CompositeFormat FolderPathsDifferent = CompositeFormat.Parse(Messages.FolderPathsDifferent);
        internal static readonly CompositeFormat FileUpdatedBeforeCapture = CompositeFormat.Parse(Messages.FileUpdatedBeforeCapture);
        internal static readonly CompositeFormat HeadersLine = CompositeFormat.Parse(Messages.HeadersLine);
        internal static readonly CompositeFormat IndexSetLine = CompositeFormat.Parse(Messages.IndexSetLine);
        internal static readonly CompositeFormat RequiredHeaderNotFound = CompositeFormat.Parse(Messages.RequiredHeaderNotFound);
        internal static readonly CompositeFormat SheetHeadersLine = CompositeFormat.Parse(Messages.SheetHeadersLine);
        internal static readonly CompositeFormat RecordHeadersLine = CompositeFormat.Parse(Messages.RecordHeadersLine);
        internal static readonly CompositeFormat HeaderCaseSensitivity = CompositeFormat.Parse(Messages.HeaderCaseSensitivity);
        internal static readonly CompositeFormat SheetNotFound = CompositeFormat.Parse(Messages.SheetNotFound);
        internal static readonly CompositeFormat UnexpectedEndOfSheet = CompositeFormat.Parse(Messages.UnexpectedEndOfSheet);
        internal static readonly CompositeFormat UnexpectedEndOfSheetWithStartCell = CompositeFormat.Parse(Messages.UnexpectedEndOfSheetWithStartCell);
        internal static readonly CompositeFormat FileOrDirectoryNotExist = CompositeFormat.Parse(Messages.FileOrDirectoryNotExist);
        internal static readonly CompositeFormat DirectoryAlreadyHasFiles = CompositeFormat.Parse(Messages.DirectoryAlreadyHasFiles);
        internal static readonly CompositeFormat ParseErrorCount = CompositeFormat.Parse(Messages.ParseErrorCount);
    }
}
